// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/triasbrata/mihon-manga-server/internal/service"
)

// MockConvertService is an autogenerated mock type for the ConvertService type
type MockConvertService struct {
	mock.Mock
}

type MockConvertService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConvertService) EXPECT() *MockConvertService_Expecter {
	return &MockConvertService_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function with given fields: ctx, req
func (_m *MockConvertService) Convert(ctx context.Context, req domain.ConvertRequest) (service.ConvertResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 service.ConvertResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConvertRequest) (service.ConvertResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConvertRequest) service.ConvertResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(service.ConvertResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ConvertRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConvertService_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MockConvertService_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ConvertRequest
func (_e *MockConvertService_Expecter) Convert(ctx interface{}, req interface{}) *MockConvertService_Convert_Call {
	return &MockConvertService_Convert_Call{Call: _e.mock.On("Convert", ctx, req)}
}

func (_c *MockConvertService_Convert_Call) Run(run func(ctx context.Context, req domain.ConvertRequest)) *MockConvertService_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ConvertRequest))
	})
	return _c
}

func (_c *MockConvertService_Convert_Call) Return(_a0 service.ConvertResult, _a1 error) *MockConvertService_Convert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConvertService_Convert_Call) RunAndReturn(run func(context.Context, domain.ConvertRequest) (service.ConvertResult, error)) *MockConvertService_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// Job provides a mock function with given fields: ctx, id
func (_m *MockConvertService) Job(ctx context.Context, id string) (domain.ConvertJob, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Job")
	}

	var r0 domain.ConvertJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ConvertJob, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ConvertJob); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.ConvertJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConvertService_Job_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Job'
type MockConvertService_Job_Call struct {
	*mock.Call
}

// Job is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConvertService_Expecter) Job(ctx interface{}, id interface{}) *MockConvertService_Job_Call {
	return &MockConvertService_Job_Call{Call: _e.mock.On("Job", ctx, id)}
}

func (_c *MockConvertService_Job_Call) Run(run func(ctx context.Context, id string)) *MockConvertService_Job_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConvertService_Job_Call) Return(_a0 domain.ConvertJob, _a1 error) *MockConvertService_Job_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConvertService_Job_Call) RunAndReturn(run func(context.Context, string) (domain.ConvertJob, error)) *MockConvertService_Job_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConvertService creates a new instance of MockConvertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConvertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConvertService {
	mock := &MockConvertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
