// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTaxonomyService is an autogenerated mock type for the TaxonomyService type
type MockTaxonomyService struct {
	mock.Mock
}

type MockTaxonomyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaxonomyService) EXPECT() *MockTaxonomyService_Expecter {
	return &MockTaxonomyService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, kind, name
func (_m *MockTaxonomyService) Create(ctx context.Context, kind domain.TaxonomyKind, name string) (domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) (domain.Taxonomy, error)); ok {
		return rf(ctx, kind, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) domain.Taxonomy); ok {
		r0 = rf(ctx, kind, name)
	} else {
		r0 = ret.Get(0).(domain.Taxonomy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind, string) error); ok {
		r1 = rf(ctx, kind, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaxonomyService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaxonomyService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - name string
func (_e *MockTaxonomyService_Expecter) Create(ctx interface{}, kind interface{}, name interface{}) *MockTaxonomyService_Create_Call {
	return &MockTaxonomyService_Create_Call{Call: _e.mock.On("Create", ctx, kind, name)}
}

func (_c *MockTaxonomyService_Create_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, name string)) *MockTaxonomyService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string))
	})
	return _c
}

func (_c *MockTaxonomyService_Create_Call) Return(_a0 domain.Taxonomy, _a1 error) *MockTaxonomyService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaxonomyService_Create_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string) (domain.Taxonomy, error)) *MockTaxonomyService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, kind, id
func (_m *MockTaxonomyService) Delete(ctx context.Context, kind domain.TaxonomyKind, id string) error {
	ret := _m.Called(ctx, kind, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) error); ok {
		r0 = rf(ctx, kind, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaxonomyService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaxonomyService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - id string
func (_e *MockTaxonomyService_Expecter) Delete(ctx interface{}, kind interface{}, id interface{}) *MockTaxonomyService_Delete_Call {
	return &MockTaxonomyService_Delete_Call{Call: _e.mock.On("Delete", ctx, kind, id)}
}

func (_c *MockTaxonomyService_Delete_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, id string)) *MockTaxonomyService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string))
	})
	return _c
}

func (_c *MockTaxonomyService_Delete_Call) Return(_a0 error) *MockTaxonomyService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaxonomyService_Delete_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string) error) *MockTaxonomyService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, kind
func (_m *MockTaxonomyService) List(ctx context.Context, kind domain.TaxonomyKind) ([]domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind) ([]domain.Taxonomy, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind) []domain.Taxonomy); ok {
		r0 = rf(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Taxonomy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaxonomyService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaxonomyService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
func (_e *MockTaxonomyService_Expecter) List(ctx interface{}, kind interface{}) *MockTaxonomyService_List_Call {
	return &MockTaxonomyService_List_Call{Call: _e.mock.On("List", ctx, kind)}
}

func (_c *MockTaxonomyService_List_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind)) *MockTaxonomyService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind))
	})
	return _c
}

func (_c *MockTaxonomyService_List_Call) Return(_a0 []domain.Taxonomy, _a1 error) *MockTaxonomyService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaxonomyService_List_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind) ([]domain.Taxonomy, error)) *MockTaxonomyService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, kind, id, name
func (_m *MockTaxonomyService) Update(ctx context.Context, kind domain.TaxonomyKind, id string, name string) (domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string, string) (domain.Taxonomy, error)); ok {
		return rf(ctx, kind, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string, string) domain.Taxonomy); ok {
		r0 = rf(ctx, kind, id, name)
	} else {
		r0 = ret.Get(0).(domain.Taxonomy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind, string, string) error); ok {
		r1 = rf(ctx, kind, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaxonomyService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaxonomyService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - id string
//   - name string
func (_e *MockTaxonomyService_Expecter) Update(ctx interface{}, kind interface{}, id interface{}, name interface{}) *MockTaxonomyService_Update_Call {
	return &MockTaxonomyService_Update_Call{Call: _e.mock.On("Update", ctx, kind, id, name)}
}

func (_c *MockTaxonomyService_Update_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, id string, name string)) *MockTaxonomyService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTaxonomyService_Update_Call) Return(_a0 domain.Taxonomy, _a1 error) *MockTaxonomyService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaxonomyService_Update_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string, string) (domain.Taxonomy, error)) *MockTaxonomyService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaxonomyService creates a new instance of MockTaxonomyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaxonomyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaxonomyService {
	mock := &MockTaxonomyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
