// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/triasbrata/mihon-manga-server/internal/service"
)

// MockAdService is an autogenerated mock type for the AdService type
type MockAdService struct {
	mock.Mock
}

type MockAdService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdService) EXPECT() *MockAdService_Expecter {
	return &MockAdService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockAdService) Create(ctx context.Context, req domain.AdWriteRequest) (domain.StoredAd, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AdWriteRequest) (domain.StoredAd, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AdWriteRequest) domain.StoredAd); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.StoredAd)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AdWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.AdWriteRequest
func (_e *MockAdService_Expecter) Create(ctx interface{}, req interface{}) *MockAdService_Create_Call {
	return &MockAdService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockAdService_Create_Call) Run(run func(ctx context.Context, req domain.AdWriteRequest)) *MockAdService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AdWriteRequest))
	})
	return _c
}

func (_c *MockAdService_Create_Call) Return(_a0 domain.StoredAd, _a1 error) *MockAdService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_Create_Call) RunAndReturn(run func(context.Context, domain.AdWriteRequest) (domain.StoredAd, error)) *MockAdService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAdService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdService_Expecter) Delete(ctx interface{}, id interface{}) *MockAdService_Delete_Call {
	return &MockAdService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAdService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAdService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdService_Delete_Call) Return(_a0 error) *MockAdService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAdService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAdService) Get(ctx context.Context, id string) (domain.StoredAd, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StoredAd, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StoredAd); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.StoredAd)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAdService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdService_Expecter) Get(ctx interface{}, id interface{}) *MockAdService_Get_Call {
	return &MockAdService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAdService_Get_Call) Run(run func(ctx context.Context, id string)) *MockAdService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdService_Get_Call) Return(_a0 domain.StoredAd, _a1 error) *MockAdService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_Get_Call) RunAndReturn(run func(context.Context, string) (domain.StoredAd, error)) *MockAdService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockAdService) List(ctx context.Context) ([]domain.StoredAd, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.StoredAd, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.StoredAd); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StoredAd)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAdService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdService_Expecter) List(ctx interface{}) *MockAdService_List_Call {
	return &MockAdService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAdService_List_Call) Run(run func(ctx context.Context)) *MockAdService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdService_List_Call) Return(_a0 []domain.StoredAd, _a1 error) *MockAdService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_List_Call) RunAndReturn(run func(context.Context) ([]domain.StoredAd, error)) *MockAdService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx, placement
func (_m *MockAdService) ListActive(ctx context.Context, placement string) ([]domain.Ad, error) {
	ret := _m.Called(ctx, placement)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []domain.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Ad, error)); ok {
		return rf(ctx, placement)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Ad); ok {
		r0 = rf(ctx, placement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placement)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockAdService_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
//   - placement string
func (_e *MockAdService_Expecter) ListActive(ctx interface{}, placement interface{}) *MockAdService_ListActive_Call {
	return &MockAdService_ListActive_Call{Call: _e.mock.On("ListActive", ctx, placement)}
}

func (_c *MockAdService_ListActive_Call) Run(run func(ctx context.Context, placement string)) *MockAdService_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdService_ListActive_Call) Return(_a0 []domain.Ad, _a1 error) *MockAdService_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_ListActive_Call) RunAndReturn(run func(context.Context, string) ([]domain.Ad, error)) *MockAdService_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// PresignUpload provides a mock function with given fields: ctx, contentType
func (_m *MockAdService) PresignUpload(ctx context.Context, contentType string) (service.PresignItem, error) {
	ret := _m.Called(ctx, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignUpload")
	}

	var r0 service.PresignItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (service.PresignItem, error)); ok {
		return rf(ctx, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) service.PresignItem); ok {
		r0 = rf(ctx, contentType)
	} else {
		r0 = ret.Get(0).(service.PresignItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_PresignUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUpload'
type MockAdService_PresignUpload_Call struct {
	*mock.Call
}

// PresignUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
func (_e *MockAdService_Expecter) PresignUpload(ctx interface{}, contentType interface{}) *MockAdService_PresignUpload_Call {
	return &MockAdService_PresignUpload_Call{Call: _e.mock.On("PresignUpload", ctx, contentType)}
}

func (_c *MockAdService_PresignUpload_Call) Run(run func(ctx context.Context, contentType string)) *MockAdService_PresignUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdService_PresignUpload_Call) Return(_a0 service.PresignItem, _a1 error) *MockAdService_PresignUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_PresignUpload_Call) RunAndReturn(run func(context.Context, string) (service.PresignItem, error)) *MockAdService_PresignUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockAdService) Update(ctx context.Context, id string, req domain.AdWriteRequest) (domain.StoredAd, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AdWriteRequest) (domain.StoredAd, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AdWriteRequest) domain.StoredAd); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.StoredAd)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AdWriteRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req domain.AdWriteRequest
func (_e *MockAdService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockAdService_Update_Call {
	return &MockAdService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockAdService_Update_Call) Run(run func(ctx context.Context, id string, req domain.AdWriteRequest)) *MockAdService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.AdWriteRequest))
	})
	return _c
}

func (_c *MockAdService_Update_Call) Return(_a0 domain.StoredAd, _a1 error) *MockAdService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdService_Update_Call) RunAndReturn(run func(context.Context, string, domain.AdWriteRequest) (domain.StoredAd, error)) *MockAdService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdService creates a new instance of MockAdService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdService {
	mock := &MockAdService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
