// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaService is an autogenerated mock type for the MediaService type
type MockMediaService struct {
	mock.Mock
}

type MockMediaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaService) EXPECT() *MockMediaService_Expecter {
	return &MockMediaService_Expecter{mock: &_m.Mock}
}

// ChapterNeighbors provides a mock function with given fields: ctx, chapterID
func (_m *MockMediaService) ChapterNeighbors(ctx context.Context, chapterID string) (domain.ChapterNeighbors, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for ChapterNeighbors")
	}

	var r0 domain.ChapterNeighbors
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ChapterNeighbors, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ChapterNeighbors); ok {
		r0 = rf(ctx, chapterID)
	} else {
		r0 = ret.Get(0).(domain.ChapterNeighbors)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_ChapterNeighbors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChapterNeighbors'
type MockMediaService_ChapterNeighbors_Call struct {
	*mock.Call
}

// ChapterNeighbors is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
func (_e *MockMediaService_Expecter) ChapterNeighbors(ctx interface{}, chapterID interface{}) *MockMediaService_ChapterNeighbors_Call {
	return &MockMediaService_ChapterNeighbors_Call{Call: _e.mock.On("ChapterNeighbors", ctx, chapterID)}
}

func (_c *MockMediaService_ChapterNeighbors_Call) Run(run func(ctx context.Context, chapterID string)) *MockMediaService_ChapterNeighbors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_ChapterNeighbors_Call) Return(_a0 domain.ChapterNeighbors, _a1 error) *MockMediaService_ChapterNeighbors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_ChapterNeighbors_Call) RunAndReturn(run func(context.Context, string) (domain.ChapterNeighbors, error)) *MockMediaService_ChapterNeighbors_Call {
	_c.Call.Return(run)
	return _c
}

// ChapterPagesAdmin provides a mock function with given fields: ctx, chapterID
func (_m *MockMediaService) ChapterPagesAdmin(ctx context.Context, chapterID string) ([]domain.AdminPage, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for ChapterPagesAdmin")
	}

	var r0 []domain.AdminPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.AdminPage, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.AdminPage); ok {
		r0 = rf(ctx, chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AdminPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_ChapterPagesAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChapterPagesAdmin'
type MockMediaService_ChapterPagesAdmin_Call struct {
	*mock.Call
}

// ChapterPagesAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
func (_e *MockMediaService_Expecter) ChapterPagesAdmin(ctx interface{}, chapterID interface{}) *MockMediaService_ChapterPagesAdmin_Call {
	return &MockMediaService_ChapterPagesAdmin_Call{Call: _e.mock.On("ChapterPagesAdmin", ctx, chapterID)}
}

func (_c *MockMediaService_ChapterPagesAdmin_Call) Run(run func(ctx context.Context, chapterID string)) *MockMediaService_ChapterPagesAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_ChapterPagesAdmin_Call) Return(_a0 []domain.AdminPage, _a1 error) *MockMediaService_ChapterPagesAdmin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_ChapterPagesAdmin_Call) RunAndReturn(run func(context.Context, string) ([]domain.AdminPage, error)) *MockMediaService_ChapterPagesAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Chapters provides a mock function with given fields: ctx, mediaID
func (_m *MockMediaService) Chapters(ctx context.Context, mediaID string) ([]domain.Chapter, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for Chapters")
	}

	var r0 []domain.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Chapter, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Chapter); ok {
		r0 = rf(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Chapters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chapters'
type MockMediaService_Chapters_Call struct {
	*mock.Call
}

// Chapters is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID string
func (_e *MockMediaService_Expecter) Chapters(ctx interface{}, mediaID interface{}) *MockMediaService_Chapters_Call {
	return &MockMediaService_Chapters_Call{Call: _e.mock.On("Chapters", ctx, mediaID)}
}

func (_c *MockMediaService_Chapters_Call) Run(run func(ctx context.Context, mediaID string)) *MockMediaService_Chapters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_Chapters_Call) Return(_a0 []domain.Chapter, _a1 error) *MockMediaService_Chapters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Chapters_Call) RunAndReturn(run func(context.Context, string) ([]domain.Chapter, error)) *MockMediaService_Chapters_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChapter provides a mock function with given fields: ctx, req
func (_m *MockMediaService) CreateChapter(ctx context.Context, req domain.ChapterWriteRequest) (domain.Chapter, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 domain.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChapterWriteRequest) (domain.Chapter, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChapterWriteRequest) domain.Chapter); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Chapter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChapterWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_CreateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChapter'
type MockMediaService_CreateChapter_Call struct {
	*mock.Call
}

// CreateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ChapterWriteRequest
func (_e *MockMediaService_Expecter) CreateChapter(ctx interface{}, req interface{}) *MockMediaService_CreateChapter_Call {
	return &MockMediaService_CreateChapter_Call{Call: _e.mock.On("CreateChapter", ctx, req)}
}

func (_c *MockMediaService_CreateChapter_Call) Run(run func(ctx context.Context, req domain.ChapterWriteRequest)) *MockMediaService_CreateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChapterWriteRequest))
	})
	return _c
}

func (_c *MockMediaService_CreateChapter_Call) Return(_a0 domain.Chapter, _a1 error) *MockMediaService_CreateChapter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_CreateChapter_Call) RunAndReturn(run func(context.Context, domain.ChapterWriteRequest) (domain.Chapter, error)) *MockMediaService_CreateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMedia provides a mock function with given fields: ctx, req
func (_m *MockMediaService) CreateMedia(ctx context.Context, req domain.MediaWriteRequest) (domain.Media, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedia")
	}

	var r0 domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MediaWriteRequest) (domain.Media, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MediaWriteRequest) domain.Media); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MediaWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_CreateMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMedia'
type MockMediaService_CreateMedia_Call struct {
	*mock.Call
}

// CreateMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.MediaWriteRequest
func (_e *MockMediaService_Expecter) CreateMedia(ctx interface{}, req interface{}) *MockMediaService_CreateMedia_Call {
	return &MockMediaService_CreateMedia_Call{Call: _e.mock.On("CreateMedia", ctx, req)}
}

func (_c *MockMediaService_CreateMedia_Call) Run(run func(ctx context.Context, req domain.MediaWriteRequest)) *MockMediaService_CreateMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MediaWriteRequest))
	})
	return _c
}

func (_c *MockMediaService_CreateMedia_Call) Return(_a0 domain.Media, _a1 error) *MockMediaService_CreateMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_CreateMedia_Call) RunAndReturn(run func(context.Context, domain.MediaWriteRequest) (domain.Media, error)) *MockMediaService_CreateMedia_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChapter provides a mock function with given fields: ctx, id
func (_m *MockMediaService) DeleteChapter(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaService_DeleteChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChapter'
type MockMediaService_DeleteChapter_Call struct {
	*mock.Call
}

// DeleteChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaService_Expecter) DeleteChapter(ctx interface{}, id interface{}) *MockMediaService_DeleteChapter_Call {
	return &MockMediaService_DeleteChapter_Call{Call: _e.mock.On("DeleteChapter", ctx, id)}
}

func (_c *MockMediaService_DeleteChapter_Call) Run(run func(ctx context.Context, id string)) *MockMediaService_DeleteChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_DeleteChapter_Call) Return(_a0 error) *MockMediaService_DeleteChapter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaService_DeleteChapter_Call) RunAndReturn(run func(context.Context, string) error) *MockMediaService_DeleteChapter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChapterPage provides a mock function with given fields: ctx, chapterID, idx
func (_m *MockMediaService) DeleteChapterPage(ctx context.Context, chapterID string, idx int) error {
	ret := _m.Called(ctx, chapterID, idx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapterPage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, chapterID, idx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaService_DeleteChapterPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChapterPage'
type MockMediaService_DeleteChapterPage_Call struct {
	*mock.Call
}

// DeleteChapterPage is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
//   - idx int
func (_e *MockMediaService_Expecter) DeleteChapterPage(ctx interface{}, chapterID interface{}, idx interface{}) *MockMediaService_DeleteChapterPage_Call {
	return &MockMediaService_DeleteChapterPage_Call{Call: _e.mock.On("DeleteChapterPage", ctx, chapterID, idx)}
}

func (_c *MockMediaService_DeleteChapterPage_Call) Run(run func(ctx context.Context, chapterID string, idx int)) *MockMediaService_DeleteChapterPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockMediaService_DeleteChapterPage_Call) Return(_a0 error) *MockMediaService_DeleteChapterPage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaService_DeleteChapterPage_Call) RunAndReturn(run func(context.Context, string, int) error) *MockMediaService_DeleteChapterPage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChapters provides a mock function with given fields: ctx, ids
func (_m *MockMediaService) DeleteChapters(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaService_DeleteChapters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChapters'
type MockMediaService_DeleteChapters_Call struct {
	*mock.Call
}

// DeleteChapters is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockMediaService_Expecter) DeleteChapters(ctx interface{}, ids interface{}) *MockMediaService_DeleteChapters_Call {
	return &MockMediaService_DeleteChapters_Call{Call: _e.mock.On("DeleteChapters", ctx, ids)}
}

func (_c *MockMediaService_DeleteChapters_Call) Run(run func(ctx context.Context, ids []string)) *MockMediaService_DeleteChapters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockMediaService_DeleteChapters_Call) Return(_a0 error) *MockMediaService_DeleteChapters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaService_DeleteChapters_Call) RunAndReturn(run func(context.Context, []string) error) *MockMediaService_DeleteChapters_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMedia provides a mock function with given fields: ctx, id
func (_m *MockMediaService) DeleteMedia(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaService_DeleteMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMedia'
type MockMediaService_DeleteMedia_Call struct {
	*mock.Call
}

// DeleteMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaService_Expecter) DeleteMedia(ctx interface{}, id interface{}) *MockMediaService_DeleteMedia_Call {
	return &MockMediaService_DeleteMedia_Call{Call: _e.mock.On("DeleteMedia", ctx, id)}
}

func (_c *MockMediaService_DeleteMedia_Call) Run(run func(ctx context.Context, id string)) *MockMediaService_DeleteMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_DeleteMedia_Call) Return(_a0 error) *MockMediaService_DeleteMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaService_DeleteMedia_Call) RunAndReturn(run func(context.Context, string) error) *MockMediaService_DeleteMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Details provides a mock function with given fields: ctx, id
func (_m *MockMediaService) Details(ctx context.Context, id string) (domain.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Details")
	}

	var r0 domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Media); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Details_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Details'
type MockMediaService_Details_Call struct {
	*mock.Call
}

// Details is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaService_Expecter) Details(ctx interface{}, id interface{}) *MockMediaService_Details_Call {
	return &MockMediaService_Details_Call{Call: _e.mock.On("Details", ctx, id)}
}

func (_c *MockMediaService_Details_Call) Run(run func(ctx context.Context, id string)) *MockMediaService_Details_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_Details_Call) Return(_a0 domain.Media, _a1 error) *MockMediaService_Details_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Details_Call) RunAndReturn(run func(context.Context, string) (domain.Media, error)) *MockMediaService_Details_Call {
	_c.Call.Return(run)
	return _c
}

// Latest provides a mock function with given fields: ctx, sourceID, page, filter
func (_m *MockMediaService) Latest(ctx context.Context, sourceID string, page int, filter domain.CatalogFilter) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, page, filter)

	if len(ret) == 0 {
		panic("no return value specified for Latest")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, domain.CatalogFilter) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, page, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, domain.CatalogFilter) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, page, filter)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, domain.CatalogFilter) error); ok {
		r1 = rf(ctx, sourceID, page, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Latest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Latest'
type MockMediaService_Latest_Call struct {
	*mock.Call
}

// Latest is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - page int
//   - filter domain.CatalogFilter
func (_e *MockMediaService_Expecter) Latest(ctx interface{}, sourceID interface{}, page interface{}, filter interface{}) *MockMediaService_Latest_Call {
	return &MockMediaService_Latest_Call{Call: _e.mock.On("Latest", ctx, sourceID, page, filter)}
}

func (_c *MockMediaService_Latest_Call) Run(run func(ctx context.Context, sourceID string, page int, filter domain.CatalogFilter)) *MockMediaService_Latest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(domain.CatalogFilter))
	})
	return _c
}

func (_c *MockMediaService_Latest_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaService_Latest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Latest_Call) RunAndReturn(run func(context.Context, string, int, domain.CatalogFilter) (domain.MediaPage, error)) *MockMediaService_Latest_Call {
	_c.Call.Return(run)
	return _c
}

// Pages provides a mock function with given fields: ctx, chapterID
func (_m *MockMediaService) Pages(ctx context.Context, chapterID string) ([]domain.Page, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for Pages")
	}

	var r0 []domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Page, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Page); ok {
		r0 = rf(ctx, chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Pages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pages'
type MockMediaService_Pages_Call struct {
	*mock.Call
}

// Pages is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
func (_e *MockMediaService_Expecter) Pages(ctx interface{}, chapterID interface{}) *MockMediaService_Pages_Call {
	return &MockMediaService_Pages_Call{Call: _e.mock.On("Pages", ctx, chapterID)}
}

func (_c *MockMediaService_Pages_Call) Run(run func(ctx context.Context, chapterID string)) *MockMediaService_Pages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_Pages_Call) Return(_a0 []domain.Page, _a1 error) *MockMediaService_Pages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Pages_Call) RunAndReturn(run func(context.Context, string) ([]domain.Page, error)) *MockMediaService_Pages_Call {
	_c.Call.Return(run)
	return _c
}

// Popular provides a mock function with given fields: ctx, sourceID, page, filter
func (_m *MockMediaService) Popular(ctx context.Context, sourceID string, page int, filter domain.CatalogFilter) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, page, filter)

	if len(ret) == 0 {
		panic("no return value specified for Popular")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, domain.CatalogFilter) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, page, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, domain.CatalogFilter) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, page, filter)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, domain.CatalogFilter) error); ok {
		r1 = rf(ctx, sourceID, page, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Popular_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Popular'
type MockMediaService_Popular_Call struct {
	*mock.Call
}

// Popular is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - page int
//   - filter domain.CatalogFilter
func (_e *MockMediaService_Expecter) Popular(ctx interface{}, sourceID interface{}, page interface{}, filter interface{}) *MockMediaService_Popular_Call {
	return &MockMediaService_Popular_Call{Call: _e.mock.On("Popular", ctx, sourceID, page, filter)}
}

func (_c *MockMediaService_Popular_Call) Run(run func(ctx context.Context, sourceID string, page int, filter domain.CatalogFilter)) *MockMediaService_Popular_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(domain.CatalogFilter))
	})
	return _c
}

func (_c *MockMediaService_Popular_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaService_Popular_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Popular_Call) RunAndReturn(run func(context.Context, string, int, domain.CatalogFilter) (domain.MediaPage, error)) *MockMediaService_Popular_Call {
	_c.Call.Return(run)
	return _c
}

// Recommendations provides a mock function with given fields: ctx, sourceID, subTypes, exclude, page
func (_m *MockMediaService) Recommendations(ctx context.Context, sourceID string, subTypes []string, exclude []string, page int) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, subTypes, exclude, page)

	if len(ret) == 0 {
		panic("no return value specified for Recommendations")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, []string, int) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, subTypes, exclude, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, []string, int) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, subTypes, exclude, page)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, []string, int) error); ok {
		r1 = rf(ctx, sourceID, subTypes, exclude, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Recommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recommendations'
type MockMediaService_Recommendations_Call struct {
	*mock.Call
}

// Recommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - subTypes []string
//   - exclude []string
//   - page int
func (_e *MockMediaService_Expecter) Recommendations(ctx interface{}, sourceID interface{}, subTypes interface{}, exclude interface{}, page interface{}) *MockMediaService_Recommendations_Call {
	return &MockMediaService_Recommendations_Call{Call: _e.mock.On("Recommendations", ctx, sourceID, subTypes, exclude, page)}
}

func (_c *MockMediaService_Recommendations_Call) Run(run func(ctx context.Context, sourceID string, subTypes []string, exclude []string, page int)) *MockMediaService_Recommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].([]string), args[4].(int))
	})
	return _c
}

func (_c *MockMediaService_Recommendations_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaService_Recommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Recommendations_Call) RunAndReturn(run func(context.Context, string, []string, []string, int) (domain.MediaPage, error)) *MockMediaService_Recommendations_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, sourceID, query, page, filter
func (_m *MockMediaService) Search(ctx context.Context, sourceID string, query string, page int, filter domain.CatalogFilter) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, query, page, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, domain.CatalogFilter) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, query, page, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, domain.CatalogFilter) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, query, page, filter)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, domain.CatalogFilter) error); ok {
		r1 = rf(ctx, sourceID, query, page, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMediaService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - query string
//   - page int
//   - filter domain.CatalogFilter
func (_e *MockMediaService_Expecter) Search(ctx interface{}, sourceID interface{}, query interface{}, page interface{}, filter interface{}) *MockMediaService_Search_Call {
	return &MockMediaService_Search_Call{Call: _e.mock.On("Search", ctx, sourceID, query, page, filter)}
}

func (_c *MockMediaService_Search_Call) Run(run func(ctx context.Context, sourceID string, query string, page int, filter domain.CatalogFilter)) *MockMediaService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(domain.CatalogFilter))
	})
	return _c
}

func (_c *MockMediaService_Search_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_Search_Call) RunAndReturn(run func(context.Context, string, string, int, domain.CatalogFilter) (domain.MediaPage, error)) *MockMediaService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SubTypeCatalog provides a mock function with given fields: ctx
func (_m *MockMediaService) SubTypeCatalog(ctx context.Context) (map[domain.MediaType][]domain.SubType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubTypeCatalog")
	}

	var r0 map[domain.MediaType][]domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[domain.MediaType][]domain.SubType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[domain.MediaType][]domain.SubType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.MediaType][]domain.SubType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_SubTypeCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTypeCatalog'
type MockMediaService_SubTypeCatalog_Call struct {
	*mock.Call
}

// SubTypeCatalog is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMediaService_Expecter) SubTypeCatalog(ctx interface{}) *MockMediaService_SubTypeCatalog_Call {
	return &MockMediaService_SubTypeCatalog_Call{Call: _e.mock.On("SubTypeCatalog", ctx)}
}

func (_c *MockMediaService_SubTypeCatalog_Call) Run(run func(ctx context.Context)) *MockMediaService_SubTypeCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMediaService_SubTypeCatalog_Call) Return(_a0 map[domain.MediaType][]domain.SubType, _a1 error) *MockMediaService_SubTypeCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_SubTypeCatalog_Call) RunAndReturn(run func(context.Context) (map[domain.MediaType][]domain.SubType, error)) *MockMediaService_SubTypeCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// SubTypes provides a mock function with given fields: ctx, sourceID
func (_m *MockMediaService) SubTypes(ctx context.Context, sourceID string) ([]domain.SubType, error) {
	ret := _m.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for SubTypes")
	}

	var r0 []domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SubType, error)); ok {
		return rf(ctx, sourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SubType); ok {
		r0 = rf(ctx, sourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SubType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_SubTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTypes'
type MockMediaService_SubTypes_Call struct {
	*mock.Call
}

// SubTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
func (_e *MockMediaService_Expecter) SubTypes(ctx interface{}, sourceID interface{}) *MockMediaService_SubTypes_Call {
	return &MockMediaService_SubTypes_Call{Call: _e.mock.On("SubTypes", ctx, sourceID)}
}

func (_c *MockMediaService_SubTypes_Call) Run(run func(ctx context.Context, sourceID string)) *MockMediaService_SubTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaService_SubTypes_Call) Return(_a0 []domain.SubType, _a1 error) *MockMediaService_SubTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_SubTypes_Call) RunAndReturn(run func(context.Context, string) ([]domain.SubType, error)) *MockMediaService_SubTypes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChapter provides a mock function with given fields: ctx, id, req
func (_m *MockMediaService) UpdateChapter(ctx context.Context, id string, req domain.ChapterWriteRequest) (domain.Chapter, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 domain.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ChapterWriteRequest) (domain.Chapter, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ChapterWriteRequest) domain.Chapter); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.Chapter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.ChapterWriteRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_UpdateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChapter'
type MockMediaService_UpdateChapter_Call struct {
	*mock.Call
}

// UpdateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req domain.ChapterWriteRequest
func (_e *MockMediaService_Expecter) UpdateChapter(ctx interface{}, id interface{}, req interface{}) *MockMediaService_UpdateChapter_Call {
	return &MockMediaService_UpdateChapter_Call{Call: _e.mock.On("UpdateChapter", ctx, id, req)}
}

func (_c *MockMediaService_UpdateChapter_Call) Run(run func(ctx context.Context, id string, req domain.ChapterWriteRequest)) *MockMediaService_UpdateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ChapterWriteRequest))
	})
	return _c
}

func (_c *MockMediaService_UpdateChapter_Call) Return(_a0 domain.Chapter, _a1 error) *MockMediaService_UpdateChapter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_UpdateChapter_Call) RunAndReturn(run func(context.Context, string, domain.ChapterWriteRequest) (domain.Chapter, error)) *MockMediaService_UpdateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMedia provides a mock function with given fields: ctx, id, req
func (_m *MockMediaService) UpdateMedia(ctx context.Context, id string, req domain.MediaWriteRequest) (domain.Media, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMedia")
	}

	var r0 domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MediaWriteRequest) (domain.Media, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MediaWriteRequest) domain.Media); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.MediaWriteRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaService_UpdateMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMedia'
type MockMediaService_UpdateMedia_Call struct {
	*mock.Call
}

// UpdateMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req domain.MediaWriteRequest
func (_e *MockMediaService_Expecter) UpdateMedia(ctx interface{}, id interface{}, req interface{}) *MockMediaService_UpdateMedia_Call {
	return &MockMediaService_UpdateMedia_Call{Call: _e.mock.On("UpdateMedia", ctx, id, req)}
}

func (_c *MockMediaService_UpdateMedia_Call) Run(run func(ctx context.Context, id string, req domain.MediaWriteRequest)) *MockMediaService_UpdateMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.MediaWriteRequest))
	})
	return _c
}

func (_c *MockMediaService_UpdateMedia_Call) Return(_a0 domain.Media, _a1 error) *MockMediaService_UpdateMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaService_UpdateMedia_Call) RunAndReturn(run func(context.Context, string, domain.MediaWriteRequest) (domain.Media, error)) *MockMediaService_UpdateMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaService creates a new instance of MockMediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaService {
	mock := &MockMediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
