// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSubTypeService is an autogenerated mock type for the SubTypeService type
type MockSubTypeService struct {
	mock.Mock
}

type MockSubTypeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubTypeService) EXPECT() *MockSubTypeService_Expecter {
	return &MockSubTypeService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockSubTypeService) Create(ctx context.Context, req domain.SubTypeWriteRequest) (domain.SubType, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SubTypeWriteRequest) (domain.SubType, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SubTypeWriteRequest) domain.SubType); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.SubType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SubTypeWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubTypeService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubTypeService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.SubTypeWriteRequest
func (_e *MockSubTypeService_Expecter) Create(ctx interface{}, req interface{}) *MockSubTypeService_Create_Call {
	return &MockSubTypeService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockSubTypeService_Create_Call) Run(run func(ctx context.Context, req domain.SubTypeWriteRequest)) *MockSubTypeService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SubTypeWriteRequest))
	})
	return _c
}

func (_c *MockSubTypeService_Create_Call) Return(_a0 domain.SubType, _a1 error) *MockSubTypeService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubTypeService_Create_Call) RunAndReturn(run func(context.Context, domain.SubTypeWriteRequest) (domain.SubType, error)) *MockSubTypeService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, slug
func (_m *MockSubTypeService) Delete(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubTypeService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubTypeService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockSubTypeService_Expecter) Delete(ctx interface{}, slug interface{}) *MockSubTypeService_Delete_Call {
	return &MockSubTypeService_Delete_Call{Call: _e.mock.On("Delete", ctx, slug)}
}

func (_c *MockSubTypeService_Delete_Call) Run(run func(ctx context.Context, slug string)) *MockSubTypeService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubTypeService_Delete_Call) Return(_a0 error) *MockSubTypeService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubTypeService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSubTypeService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockSubTypeService) List(ctx context.Context) ([]domain.SubType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SubType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SubType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SubType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubTypeService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubTypeService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubTypeService_Expecter) List(ctx interface{}) *MockSubTypeService_List_Call {
	return &MockSubTypeService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSubTypeService_List_Call) Run(run func(ctx context.Context)) *MockSubTypeService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubTypeService_List_Call) Return(_a0 []domain.SubType, _a1 error) *MockSubTypeService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubTypeService_List_Call) RunAndReturn(run func(context.Context) ([]domain.SubType, error)) *MockSubTypeService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, slug, req
func (_m *MockSubTypeService) Update(ctx context.Context, slug string, req domain.SubTypeWriteRequest) (domain.SubType, error) {
	ret := _m.Called(ctx, slug, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubTypeWriteRequest) (domain.SubType, error)); ok {
		return rf(ctx, slug, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubTypeWriteRequest) domain.SubType); ok {
		r0 = rf(ctx, slug, req)
	} else {
		r0 = ret.Get(0).(domain.SubType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.SubTypeWriteRequest) error); ok {
		r1 = rf(ctx, slug, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubTypeService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubTypeService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - req domain.SubTypeWriteRequest
func (_e *MockSubTypeService_Expecter) Update(ctx interface{}, slug interface{}, req interface{}) *MockSubTypeService_Update_Call {
	return &MockSubTypeService_Update_Call{Call: _e.mock.On("Update", ctx, slug, req)}
}

func (_c *MockSubTypeService_Update_Call) Run(run func(ctx context.Context, slug string, req domain.SubTypeWriteRequest)) *MockSubTypeService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubTypeWriteRequest))
	})
	return _c
}

func (_c *MockSubTypeService_Update_Call) Return(_a0 domain.SubType, _a1 error) *MockSubTypeService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubTypeService_Update_Call) RunAndReturn(run func(context.Context, string, domain.SubTypeWriteRequest) (domain.SubType, error)) *MockSubTypeService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubTypeService creates a new instance of MockSubTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubTypeService {
	mock := &MockSubTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
