// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockNovelService is an autogenerated mock type for the NovelService type
type MockNovelService struct {
	mock.Mock
}

type MockNovelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNovelService) EXPECT() *MockNovelService_Expecter {
	return &MockNovelService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockNovelService) Register(ctx context.Context, req domain.NovelRegisterRequest) (domain.Page, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NovelRegisterRequest) (domain.Page, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NovelRegisterRequest) domain.Page); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NovelRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNovelService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockNovelService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.NovelRegisterRequest
func (_e *MockNovelService_Expecter) Register(ctx interface{}, req interface{}) *MockNovelService_Register_Call {
	return &MockNovelService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockNovelService_Register_Call) Run(run func(ctx context.Context, req domain.NovelRegisterRequest)) *MockNovelService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.NovelRegisterRequest))
	})
	return _c
}

func (_c *MockNovelService_Register_Call) Return(_a0 domain.Page, _a1 error) *MockNovelService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNovelService_Register_Call) RunAndReturn(run func(context.Context, domain.NovelRegisterRequest) (domain.Page, error)) *MockNovelService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNovelService creates a new instance of MockNovelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNovelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNovelService {
	mock := &MockNovelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
