// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSourceService is an autogenerated mock type for the SourceService type
type MockSourceService struct {
	mock.Mock
}

type MockSourceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceService) EXPECT() *MockSourceService_Expecter {
	return &MockSourceService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockSourceService) Create(ctx context.Context, req domain.SourceWriteRequest) (domain.Source, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SourceWriteRequest) (domain.Source, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SourceWriteRequest) domain.Source); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SourceWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSourceService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.SourceWriteRequest
func (_e *MockSourceService_Expecter) Create(ctx interface{}, req interface{}) *MockSourceService_Create_Call {
	return &MockSourceService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockSourceService_Create_Call) Run(run func(ctx context.Context, req domain.SourceWriteRequest)) *MockSourceService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SourceWriteRequest))
	})
	return _c
}

func (_c *MockSourceService_Create_Call) Return(_a0 domain.Source, _a1 error) *MockSourceService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceService_Create_Call) RunAndReturn(run func(context.Context, domain.SourceWriteRequest) (domain.Source, error)) *MockSourceService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSourceService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSourceService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSourceService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceService_Expecter) Delete(ctx interface{}, id interface{}) *MockSourceService_Delete_Call {
	return &MockSourceService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSourceService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSourceService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceService_Delete_Call) Return(_a0 error) *MockSourceService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSourceService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSourceService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockSourceService) Get(ctx context.Context, id string) (domain.Source, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Source, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Source); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSourceService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceService_Expecter) Get(ctx interface{}, id interface{}) *MockSourceService_Get_Call {
	return &MockSourceService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSourceService_Get_Call) Run(run func(ctx context.Context, id string)) *MockSourceService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceService_Get_Call) Return(_a0 domain.Source, _a1 error) *MockSourceService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceService_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Source, error)) *MockSourceService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, enabledOnly
func (_m *MockSourceService) List(ctx context.Context, enabledOnly bool) ([]domain.Source, error) {
	ret := _m.Called(ctx, enabledOnly)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Source, error)); ok {
		return rf(ctx, enabledOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []domain.Source); ok {
		r0 = rf(ctx, enabledOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, enabledOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSourceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - enabledOnly bool
func (_e *MockSourceService_Expecter) List(ctx interface{}, enabledOnly interface{}) *MockSourceService_List_Call {
	return &MockSourceService_List_Call{Call: _e.mock.On("List", ctx, enabledOnly)}
}

func (_c *MockSourceService_List_Call) Run(run func(ctx context.Context, enabledOnly bool)) *MockSourceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockSourceService_List_Call) Return(_a0 []domain.Source, _a1 error) *MockSourceService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceService_List_Call) RunAndReturn(run func(context.Context, bool) ([]domain.Source, error)) *MockSourceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockSourceService) Update(ctx context.Context, id string, req domain.SourceWriteRequest) (domain.Source, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SourceWriteRequest) (domain.Source, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SourceWriteRequest) domain.Source); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.SourceWriteRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSourceService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req domain.SourceWriteRequest
func (_e *MockSourceService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockSourceService_Update_Call {
	return &MockSourceService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockSourceService_Update_Call) Run(run func(ctx context.Context, id string, req domain.SourceWriteRequest)) *MockSourceService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SourceWriteRequest))
	})
	return _c
}

func (_c *MockSourceService_Update_Call) Return(_a0 domain.Source, _a1 error) *MockSourceService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceService_Update_Call) RunAndReturn(run func(context.Context, string, domain.SourceWriteRequest) (domain.Source, error)) *MockSourceService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourceService creates a new instance of MockSourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceService {
	mock := &MockSourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
