// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/triasbrata/mihon-manga-server/internal/service"
)

// MockConvertService is an autogenerated mock type for the ConvertService type
type MockConvertService struct {
	mock.Mock
}

type MockConvertService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConvertService) EXPECT() *MockConvertService_Expecter {
	return &MockConvertService_Expecter{mock: &_m.Mock}
}

// PresignUploads provides a mock function with given fields: ctx, count, contentType
func (_m *MockConvertService) PresignUploads(ctx context.Context, count int, contentType string) (service.PresignResult, error) {
	ret := _m.Called(ctx, count, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignUploads")
	}

	var r0 service.PresignResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (service.PresignResult, error)); ok {
		return rf(ctx, count, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) service.PresignResult); ok {
		r0 = rf(ctx, count, contentType)
	} else {
		r0 = ret.Get(0).(service.PresignResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, count, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConvertService_PresignUploads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUploads'
type MockConvertService_PresignUploads_Call struct {
	*mock.Call
}

// PresignUploads is a helper method to define mock.On call
//   - ctx context.Context
//   - count int
//   - contentType string
func (_e *MockConvertService_Expecter) PresignUploads(ctx interface{}, count interface{}, contentType interface{}) *MockConvertService_PresignUploads_Call {
	return &MockConvertService_PresignUploads_Call{Call: _e.mock.On("PresignUploads", ctx, count, contentType)}
}

func (_c *MockConvertService_PresignUploads_Call) Run(run func(ctx context.Context, count int, contentType string)) *MockConvertService_PresignUploads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockConvertService_PresignUploads_Call) Return(_a0 service.PresignResult, _a1 error) *MockConvertService_PresignUploads_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConvertService_PresignUploads_Call) RunAndReturn(run func(context.Context, int, string) (service.PresignResult, error)) *MockConvertService_PresignUploads_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPages provides a mock function with given fields: ctx, chapterID, pages
func (_m *MockConvertService) RegisterPages(ctx context.Context, chapterID string, pages []domain.StoredPage) ([]domain.Page, error) {
	ret := _m.Called(ctx, chapterID, pages)

	if len(ret) == 0 {
		panic("no return value specified for RegisterPages")
	}

	var r0 []domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.StoredPage) ([]domain.Page, error)); ok {
		return rf(ctx, chapterID, pages)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.StoredPage) []domain.Page); ok {
		r0 = rf(ctx, chapterID, pages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []domain.StoredPage) error); ok {
		r1 = rf(ctx, chapterID, pages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConvertService_RegisterPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPages'
type MockConvertService_RegisterPages_Call struct {
	*mock.Call
}

// RegisterPages is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
//   - pages []domain.StoredPage
func (_e *MockConvertService_Expecter) RegisterPages(ctx interface{}, chapterID interface{}, pages interface{}) *MockConvertService_RegisterPages_Call {
	return &MockConvertService_RegisterPages_Call{Call: _e.mock.On("RegisterPages", ctx, chapterID, pages)}
}

func (_c *MockConvertService_RegisterPages_Call) Run(run func(ctx context.Context, chapterID string, pages []domain.StoredPage)) *MockConvertService_RegisterPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.StoredPage))
	})
	return _c
}

func (_c *MockConvertService_RegisterPages_Call) Return(_a0 []domain.Page, _a1 error) *MockConvertService_RegisterPages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConvertService_RegisterPages_Call) RunAndReturn(run func(context.Context, string, []domain.StoredPage) ([]domain.Page, error)) *MockConvertService_RegisterPages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConvertService creates a new instance of MockConvertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConvertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConvertService {
	mock := &MockConvertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
