// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockVideoService is an autogenerated mock type for the VideoService type
type MockVideoService struct {
	mock.Mock
}

type MockVideoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoService) EXPECT() *MockVideoService_Expecter {
	return &MockVideoService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockVideoService) Register(ctx context.Context, req domain.VideoRegisterRequest) (domain.Page, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.VideoRegisterRequest) (domain.Page, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.VideoRegisterRequest) domain.Page); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.VideoRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVideoService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockVideoService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.VideoRegisterRequest
func (_e *MockVideoService_Expecter) Register(ctx interface{}, req interface{}) *MockVideoService_Register_Call {
	return &MockVideoService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockVideoService_Register_Call) Run(run func(ctx context.Context, req domain.VideoRegisterRequest)) *MockVideoService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.VideoRegisterRequest))
	})
	return _c
}

func (_c *MockVideoService_Register_Call) Return(_a0 domain.Page, _a1 error) *MockVideoService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVideoService_Register_Call) RunAndReturn(run func(context.Context, domain.VideoRegisterRequest) (domain.Page, error)) *MockVideoService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVideoService creates a new instance of MockVideoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoService {
	mock := &MockVideoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
