// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/triasbrata/mihon-manga-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockConnectionService is an autogenerated mock type for the ConnectionService type
type MockConnectionService struct {
	mock.Mock
}

type MockConnectionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionService) EXPECT() *MockConnectionService_Expecter {
	return &MockConnectionService_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, id, redirectURI
func (_m *MockConnectionService) Authorize(ctx context.Context, id string, redirectURI string) (string, error) {
	ret := _m.Called(ctx, id, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, id, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, id, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockConnectionService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - redirectURI string
func (_e *MockConnectionService_Expecter) Authorize(ctx interface{}, id interface{}, redirectURI interface{}) *MockConnectionService_Authorize_Call {
	return &MockConnectionService_Authorize_Call{Call: _e.mock.On("Authorize", ctx, id, redirectURI)}
}

func (_c *MockConnectionService_Authorize_Call) Run(run func(ctx context.Context, id string, redirectURI string)) *MockConnectionService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConnectionService_Authorize_Call) Return(_a0 string, _a1 error) *MockConnectionService_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Authorize_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockConnectionService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Callback provides a mock function with given fields: ctx, code, state
func (_m *MockConnectionService) Callback(ctx context.Context, code string, state string) (domain.Connection, error) {
	ret := _m.Called(ctx, code, state)

	if len(ret) == 0 {
		panic("no return value specified for Callback")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Connection, error)); ok {
		return rf(ctx, code, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Connection); ok {
		r0 = rf(ctx, code, state)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type MockConnectionService_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
func (_e *MockConnectionService_Expecter) Callback(ctx interface{}, code interface{}, state interface{}) *MockConnectionService_Callback_Call {
	return &MockConnectionService_Callback_Call{Call: _e.mock.On("Callback", ctx, code, state)}
}

func (_c *MockConnectionService_Callback_Call) Run(run func(ctx context.Context, code string, state string)) *MockConnectionService_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConnectionService_Callback_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionService_Callback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Callback_Call) RunAndReturn(run func(context.Context, string, string) (domain.Connection, error)) *MockConnectionService_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockConnectionService) Create(ctx context.Context, req domain.ConnectionWriteRequest) (domain.Connection, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConnectionWriteRequest) (domain.Connection, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConnectionWriteRequest) domain.Connection); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ConnectionWriteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConnectionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ConnectionWriteRequest
func (_e *MockConnectionService_Expecter) Create(ctx interface{}, req interface{}) *MockConnectionService_Create_Call {
	return &MockConnectionService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockConnectionService_Create_Call) Run(run func(ctx context.Context, req domain.ConnectionWriteRequest)) *MockConnectionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ConnectionWriteRequest))
	})
	return _c
}

func (_c *MockConnectionService_Create_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Create_Call) RunAndReturn(run func(context.Context, domain.ConnectionWriteRequest) (domain.Connection, error)) *MockConnectionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockConnectionService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConnectionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConnectionService_Expecter) Delete(ctx interface{}, id interface{}) *MockConnectionService_Delete_Call {
	return &MockConnectionService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockConnectionService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockConnectionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnectionService_Delete_Call) Return(_a0 error) *MockConnectionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockConnectionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockConnectionService) Get(ctx context.Context, id string) (domain.Connection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Connection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Connection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConnectionService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConnectionService_Expecter) Get(ctx interface{}, id interface{}) *MockConnectionService_Get_Call {
	return &MockConnectionService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockConnectionService_Get_Call) Run(run func(ctx context.Context, id string)) *MockConnectionService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnectionService_Get_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Connection, error)) *MockConnectionService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockConnectionService) List(ctx context.Context) ([]domain.Connection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Connection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Connection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConnectionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectionService_Expecter) List(ctx interface{}) *MockConnectionService_List_Call {
	return &MockConnectionService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockConnectionService_List_Call) Run(run func(ctx context.Context)) *MockConnectionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnectionService_List_Call) Return(_a0 []domain.Connection, _a1 error) *MockConnectionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_List_Call) RunAndReturn(run func(context.Context) ([]domain.Connection, error)) *MockConnectionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, id
func (_m *MockConnectionService) Refresh(ctx context.Context, id string) (domain.Connection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Connection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Connection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockConnectionService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConnectionService_Expecter) Refresh(ctx interface{}, id interface{}) *MockConnectionService_Refresh_Call {
	return &MockConnectionService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, id)}
}

func (_c *MockConnectionService_Refresh_Call) Run(run func(ctx context.Context, id string)) *MockConnectionService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnectionService_Refresh_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Refresh_Call) RunAndReturn(run func(context.Context, string) (domain.Connection, error)) *MockConnectionService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockConnectionService) Update(ctx context.Context, id string, req domain.ConnectionWriteRequest) (domain.Connection, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ConnectionWriteRequest) (domain.Connection, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ConnectionWriteRequest) domain.Connection); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.ConnectionWriteRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockConnectionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req domain.ConnectionWriteRequest
func (_e *MockConnectionService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockConnectionService_Update_Call {
	return &MockConnectionService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockConnectionService_Update_Call) Run(run func(ctx context.Context, id string, req domain.ConnectionWriteRequest)) *MockConnectionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ConnectionWriteRequest))
	})
	return _c
}

func (_c *MockConnectionService_Update_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionService_Update_Call) RunAndReturn(run func(context.Context, string, domain.ConnectionWriteRequest) (domain.Connection, error)) *MockConnectionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionService creates a new instance of MockConnectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionService {
	mock := &MockConnectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
