import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// routeTree.gen.ts is generated by the TanStack Start vite plugin on first run.
export function getRouter() {
  return createRouter({ routeTree, scrollRestoration: true })
}
