// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, sql, params
func (_m *MockQuerier) Exec(ctx context.Context, sql string, params ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = rf(ctx, sql, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockQuerier_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - params ...any
func (_e *MockQuerier_Expecter) Exec(ctx interface{}, sql interface{}, params ...interface{}) *MockQuerier_Exec_Call {
	return &MockQuerier_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, params...)...)}
}

func (_c *MockQuerier_Exec_Call) Run(run func(ctx context.Context, sql string, params ...any)) *MockQuerier_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQuerier_Exec_Call) Return(_a0 error) *MockQuerier_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) error) *MockQuerier_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, params
func (_m *MockQuerier) Query(ctx context.Context, sql string, params ...any) ([]map[string]any, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []map[string]any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) ([]map[string]any, error)); ok {
		return rf(ctx, sql, params...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) []map[string]any); ok {
		r0 = rf(ctx, sql, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockQuerier_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - params ...any
func (_e *MockQuerier_Expecter) Query(ctx interface{}, sql interface{}, params ...interface{}) *MockQuerier_Query_Call {
	return &MockQuerier_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, params...)...)}
}

func (_c *MockQuerier_Query_Call) Run(run func(ctx context.Context, sql string, params ...any)) *MockQuerier_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQuerier_Query_Call) Return(_a0 []map[string]any, _a1 error) *MockQuerier_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_Query_Call) RunAndReturn(run func(context.Context, string, ...any) ([]map[string]any, error)) *MockQuerier_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
