// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockOAuthClient is an autogenerated mock type for the OAuthClient type
type MockOAuthClient struct {
	mock.Mock
}

type MockOAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthClient) EXPECT() *MockOAuthClient_Expecter {
	return &MockOAuthClient_Expecter{mock: &_m.Mock}
}

// Exchange provides a mock function with given fields: ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI
func (_m *MockOAuthClient) Exchange(ctx context.Context, p domain.Provider, clientID string, clientSecret string, code string, codeVerifier string, redirectURI string) (domain.TokenResponse, error) {
	ret := _m.Called(ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 domain.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Provider, string, string, string, string, string) (domain.TokenResponse, error)); ok {
		return rf(ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Provider, string, string, string, string, string) domain.TokenResponse); ok {
		r0 = rf(ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI)
	} else {
		r0 = ret.Get(0).(domain.TokenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Provider, string, string, string, string, string) error); ok {
		r1 = rf(ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthClient_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockOAuthClient_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Provider
//   - clientID string
//   - clientSecret string
//   - code string
//   - codeVerifier string
//   - redirectURI string
func (_e *MockOAuthClient_Expecter) Exchange(ctx interface{}, p interface{}, clientID interface{}, clientSecret interface{}, code interface{}, codeVerifier interface{}, redirectURI interface{}) *MockOAuthClient_Exchange_Call {
	return &MockOAuthClient_Exchange_Call{Call: _e.mock.On("Exchange", ctx, p, clientID, clientSecret, code, codeVerifier, redirectURI)}
}

func (_c *MockOAuthClient_Exchange_Call) Run(run func(ctx context.Context, p domain.Provider, clientID string, clientSecret string, code string, codeVerifier string, redirectURI string)) *MockOAuthClient_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Provider), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockOAuthClient_Exchange_Call) Return(_a0 domain.TokenResponse, _a1 error) *MockOAuthClient_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthClient_Exchange_Call) RunAndReturn(run func(context.Context, domain.Provider, string, string, string, string, string) (domain.TokenResponse, error)) *MockOAuthClient_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, url, accessToken
func (_m *MockOAuthClient) Get(ctx context.Context, url string, accessToken string) ([]byte, int, error) {
	ret := _m.Called(ctx, url, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, int, error)); ok {
		return rf(ctx, url, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, url, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) int); ok {
		r1 = rf(ctx, url, accessToken)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, url, accessToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOAuthClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOAuthClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - accessToken string
func (_e *MockOAuthClient_Expecter) Get(ctx interface{}, url interface{}, accessToken interface{}) *MockOAuthClient_Get_Call {
	return &MockOAuthClient_Get_Call{Call: _e.mock.On("Get", ctx, url, accessToken)}
}

func (_c *MockOAuthClient_Get_Call) Run(run func(ctx context.Context, url string, accessToken string)) *MockOAuthClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthClient_Get_Call) Return(_a0 []byte, _a1 int, _a2 error) *MockOAuthClient_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOAuthClient_Get_Call) RunAndReturn(run func(context.Context, string, string) ([]byte, int, error)) *MockOAuthClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, p, clientID, clientSecret, refreshToken
func (_m *MockOAuthClient) Refresh(ctx context.Context, p domain.Provider, clientID string, clientSecret string, refreshToken string) (domain.TokenResponse, error) {
	ret := _m.Called(ctx, p, clientID, clientSecret, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 domain.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Provider, string, string, string) (domain.TokenResponse, error)); ok {
		return rf(ctx, p, clientID, clientSecret, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Provider, string, string, string) domain.TokenResponse); ok {
		r0 = rf(ctx, p, clientID, clientSecret, refreshToken)
	} else {
		r0 = ret.Get(0).(domain.TokenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Provider, string, string, string) error); ok {
		r1 = rf(ctx, p, clientID, clientSecret, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthClient_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockOAuthClient_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Provider
//   - clientID string
//   - clientSecret string
//   - refreshToken string
func (_e *MockOAuthClient_Expecter) Refresh(ctx interface{}, p interface{}, clientID interface{}, clientSecret interface{}, refreshToken interface{}) *MockOAuthClient_Refresh_Call {
	return &MockOAuthClient_Refresh_Call{Call: _e.mock.On("Refresh", ctx, p, clientID, clientSecret, refreshToken)}
}

func (_c *MockOAuthClient_Refresh_Call) Run(run func(ctx context.Context, p domain.Provider, clientID string, clientSecret string, refreshToken string)) *MockOAuthClient_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Provider), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockOAuthClient_Refresh_Call) Return(_a0 domain.TokenResponse, _a1 error) *MockOAuthClient_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthClient_Refresh_Call) RunAndReturn(run func(context.Context, domain.Provider, string, string, string) (domain.TokenResponse, error)) *MockOAuthClient_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthClient creates a new instance of MockOAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthClient {
	mock := &MockOAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
