// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockConnectionRepository is an autogenerated mock type for the ConnectionRepository type
type MockConnectionRepository struct {
	mock.Mock
}

type MockConnectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionRepository) EXPECT() *MockConnectionRepository_Expecter {
	return &MockConnectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockConnectionRepository) Create(ctx context.Context, c domain.Connection) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Connection) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConnectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c domain.Connection
func (_e *MockConnectionRepository_Expecter) Create(ctx interface{}, c interface{}) *MockConnectionRepository_Create_Call {
	return &MockConnectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockConnectionRepository_Create_Call) Run(run func(ctx context.Context, c domain.Connection)) *MockConnectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Connection))
	})
	return _c
}

func (_c *MockConnectionRepository_Create_Call) Return(_a0 error) *MockConnectionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Connection) error) *MockConnectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockConnectionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConnectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConnectionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockConnectionRepository_Delete_Call {
	return &MockConnectionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockConnectionRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockConnectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnectionRepository_Delete_Call) Return(_a0 error) *MockConnectionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockConnectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockConnectionRepository) Get(ctx context.Context, id string) (domain.Connection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Connection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Connection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Connection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConnectionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConnectionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockConnectionRepository_Get_Call {
	return &MockConnectionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockConnectionRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockConnectionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnectionRepository_Get_Call) Return(_a0 domain.Connection, _a1 error) *MockConnectionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionRepository_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Connection, error)) *MockConnectionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockConnectionRepository) List(ctx context.Context) ([]domain.Connection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Connection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Connection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConnectionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectionRepository_Expecter) List(ctx interface{}) *MockConnectionRepository_List_Call {
	return &MockConnectionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockConnectionRepository_List_Call) Run(run func(ctx context.Context)) *MockConnectionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnectionRepository_List_Call) Return(_a0 []domain.Connection, _a1 error) *MockConnectionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionRepository_List_Call) RunAndReturn(run func(context.Context) ([]domain.Connection, error)) *MockConnectionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTokens provides a mock function with given fields: ctx, id, access, refresh, tokenType, expiresAt, status, updatedAt
func (_m *MockConnectionRepository) SaveTokens(ctx context.Context, id string, access string, refresh string, tokenType string, expiresAt int64, status domain.ConnectionStatus, updatedAt int64) error {
	ret := _m.Called(ctx, id, access, refresh, tokenType, expiresAt, status, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int64, domain.ConnectionStatus, int64) error); ok {
		r0 = rf(ctx, id, access, refresh, tokenType, expiresAt, status, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectionRepository_SaveTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTokens'
type MockConnectionRepository_SaveTokens_Call struct {
	*mock.Call
}

// SaveTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - access string
//   - refresh string
//   - tokenType string
//   - expiresAt int64
//   - status domain.ConnectionStatus
//   - updatedAt int64
func (_e *MockConnectionRepository_Expecter) SaveTokens(ctx interface{}, id interface{}, access interface{}, refresh interface{}, tokenType interface{}, expiresAt interface{}, status interface{}, updatedAt interface{}) *MockConnectionRepository_SaveTokens_Call {
	return &MockConnectionRepository_SaveTokens_Call{Call: _e.mock.On("SaveTokens", ctx, id, access, refresh, tokenType, expiresAt, status, updatedAt)}
}

func (_c *MockConnectionRepository_SaveTokens_Call) Run(run func(ctx context.Context, id string, access string, refresh string, tokenType string, expiresAt int64, status domain.ConnectionStatus, updatedAt int64)) *MockConnectionRepository_SaveTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int64), args[6].(domain.ConnectionStatus), args[7].(int64))
	})
	return _c
}

func (_c *MockConnectionRepository_SaveTokens_Call) Return(_a0 error) *MockConnectionRepository_SaveTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionRepository_SaveTokens_Call) RunAndReturn(run func(context.Context, string, string, string, string, int64, domain.ConnectionStatus, int64) error) *MockConnectionRepository_SaveTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockConnectionRepository) Update(ctx context.Context, c domain.Connection) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Connection) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockConnectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c domain.Connection
func (_e *MockConnectionRepository_Expecter) Update(ctx interface{}, c interface{}) *MockConnectionRepository_Update_Call {
	return &MockConnectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *MockConnectionRepository_Update_Call) Run(run func(ctx context.Context, c domain.Connection)) *MockConnectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Connection))
	})
	return _c
}

func (_c *MockConnectionRepository_Update_Call) Return(_a0 error) *MockConnectionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionRepository_Update_Call) RunAndReturn(run func(context.Context, domain.Connection) error) *MockConnectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionRepository creates a new instance of MockConnectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionRepository {
	mock := &MockConnectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
