// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockStateStore is an autogenerated mock type for the StateStore type
type MockStateStore struct {
	mock.Mock
}

type MockStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateStore) EXPECT() *MockStateStore_Expecter {
	return &MockStateStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, state
func (_m *MockStateStore) Get(ctx context.Context, state string) (domain.AuthState, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.AuthState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.AuthState, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.AuthState); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(domain.AuthState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStateStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockStateStore_Expecter) Get(ctx interface{}, state interface{}) *MockStateStore_Get_Call {
	return &MockStateStore_Get_Call{Call: _e.mock.On("Get", ctx, state)}
}

func (_c *MockStateStore_Get_Call) Run(run func(ctx context.Context, state string)) *MockStateStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStateStore_Get_Call) Return(_a0 domain.AuthState, _a1 error) *MockStateStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStateStore_Get_Call) RunAndReturn(run func(context.Context, string) (domain.AuthState, error)) *MockStateStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, state, v, ttlSeconds
func (_m *MockStateStore) Put(ctx context.Context, state string, v domain.AuthState, ttlSeconds int) error {
	ret := _m.Called(ctx, state, v, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthState, int) error); ok {
		r0 = rf(ctx, state, v, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStateStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStateStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - v domain.AuthState
//   - ttlSeconds int
func (_e *MockStateStore_Expecter) Put(ctx interface{}, state interface{}, v interface{}, ttlSeconds interface{}) *MockStateStore_Put_Call {
	return &MockStateStore_Put_Call{Call: _e.mock.On("Put", ctx, state, v, ttlSeconds)}
}

func (_c *MockStateStore_Put_Call) Run(run func(ctx context.Context, state string, v domain.AuthState, ttlSeconds int)) *MockStateStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.AuthState), args[3].(int))
	})
	return _c
}

func (_c *MockStateStore_Put_Call) Return(_a0 error) *MockStateStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStateStore_Put_Call) RunAndReturn(run func(context.Context, string, domain.AuthState, int) error) *MockStateStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateStore creates a new instance of MockStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateStore {
	mock := &MockStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
