// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockMediaRepository is an autogenerated mock type for the MediaRepository type
type MockMediaRepository struct {
	mock.Mock
}

type MockMediaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaRepository) EXPECT() *MockMediaRepository_Expecter {
	return &MockMediaRepository_Expecter{mock: &_m.Mock}
}

// ChapterByID provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) ChapterByID(ctx context.Context, id string) (domain.Chapter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ChapterByID")
	}

	var r0 domain.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Chapter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Chapter); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Chapter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_ChapterByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChapterByID'
type MockMediaRepository_ChapterByID_Call struct {
	*mock.Call
}

// ChapterByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaRepository_Expecter) ChapterByID(ctx interface{}, id interface{}) *MockMediaRepository_ChapterByID_Call {
	return &MockMediaRepository_ChapterByID_Call{Call: _e.mock.On("ChapterByID", ctx, id)}
}

func (_c *MockMediaRepository_ChapterByID_Call) Run(run func(ctx context.Context, id string)) *MockMediaRepository_ChapterByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_ChapterByID_Call) Return(_a0 domain.Chapter, _a1 error) *MockMediaRepository_ChapterByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_ChapterByID_Call) RunAndReturn(run func(context.Context, string) (domain.Chapter, error)) *MockMediaRepository_ChapterByID_Call {
	_c.Call.Return(run)
	return _c
}

// Chapters provides a mock function with given fields: ctx, mediaID
func (_m *MockMediaRepository) Chapters(ctx context.Context, mediaID string) ([]domain.Chapter, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for Chapters")
	}

	var r0 []domain.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Chapter, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Chapter); ok {
		r0 = rf(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Chapters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chapters'
type MockMediaRepository_Chapters_Call struct {
	*mock.Call
}

// Chapters is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID string
func (_e *MockMediaRepository_Expecter) Chapters(ctx interface{}, mediaID interface{}) *MockMediaRepository_Chapters_Call {
	return &MockMediaRepository_Chapters_Call{Call: _e.mock.On("Chapters", ctx, mediaID)}
}

func (_c *MockMediaRepository_Chapters_Call) Run(run func(ctx context.Context, mediaID string)) *MockMediaRepository_Chapters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_Chapters_Call) Return(_a0 []domain.Chapter, _a1 error) *MockMediaRepository_Chapters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Chapters_Call) RunAndReturn(run func(context.Context, string) ([]domain.Chapter, error)) *MockMediaRepository_Chapters_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChapter provides a mock function with given fields: ctx, c
func (_m *MockMediaRepository) CreateChapter(ctx context.Context, c domain.Chapter) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Chapter) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_CreateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChapter'
type MockMediaRepository_CreateChapter_Call struct {
	*mock.Call
}

// CreateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - c domain.Chapter
func (_e *MockMediaRepository_Expecter) CreateChapter(ctx interface{}, c interface{}) *MockMediaRepository_CreateChapter_Call {
	return &MockMediaRepository_CreateChapter_Call{Call: _e.mock.On("CreateChapter", ctx, c)}
}

func (_c *MockMediaRepository_CreateChapter_Call) Run(run func(ctx context.Context, c domain.Chapter)) *MockMediaRepository_CreateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Chapter))
	})
	return _c
}

func (_c *MockMediaRepository_CreateChapter_Call) Return(_a0 error) *MockMediaRepository_CreateChapter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_CreateChapter_Call) RunAndReturn(run func(context.Context, domain.Chapter) error) *MockMediaRepository_CreateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMedia provides a mock function with given fields: ctx, m
func (_m *MockMediaRepository) CreateMedia(ctx context.Context, m domain.Media) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Media) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_CreateMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMedia'
type MockMediaRepository_CreateMedia_Call struct {
	*mock.Call
}

// CreateMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - m domain.Media
func (_e *MockMediaRepository_Expecter) CreateMedia(ctx interface{}, m interface{}) *MockMediaRepository_CreateMedia_Call {
	return &MockMediaRepository_CreateMedia_Call{Call: _e.mock.On("CreateMedia", ctx, m)}
}

func (_c *MockMediaRepository_CreateMedia_Call) Run(run func(ctx context.Context, m domain.Media)) *MockMediaRepository_CreateMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Media))
	})
	return _c
}

func (_c *MockMediaRepository_CreateMedia_Call) Return(_a0 error) *MockMediaRepository_CreateMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_CreateMedia_Call) RunAndReturn(run func(context.Context, domain.Media) error) *MockMediaRepository_CreateMedia_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubType provides a mock function with given fields: ctx, st
func (_m *MockMediaRepository) CreateSubType(ctx context.Context, st domain.SubType) error {
	ret := _m.Called(ctx, st)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SubType) error); ok {
		r0 = rf(ctx, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_CreateSubType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubType'
type MockMediaRepository_CreateSubType_Call struct {
	*mock.Call
}

// CreateSubType is a helper method to define mock.On call
//   - ctx context.Context
//   - st domain.SubType
func (_e *MockMediaRepository_Expecter) CreateSubType(ctx interface{}, st interface{}) *MockMediaRepository_CreateSubType_Call {
	return &MockMediaRepository_CreateSubType_Call{Call: _e.mock.On("CreateSubType", ctx, st)}
}

func (_c *MockMediaRepository_CreateSubType_Call) Run(run func(ctx context.Context, st domain.SubType)) *MockMediaRepository_CreateSubType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SubType))
	})
	return _c
}

func (_c *MockMediaRepository_CreateSubType_Call) Return(_a0 error) *MockMediaRepository_CreateSubType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_CreateSubType_Call) RunAndReturn(run func(context.Context, domain.SubType) error) *MockMediaRepository_CreateSubType_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTaxonomy provides a mock function with given fields: ctx, kind, name
func (_m *MockMediaRepository) CreateTaxonomy(ctx context.Context, kind domain.TaxonomyKind, name string) (domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaxonomy")
	}

	var r0 domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) (domain.Taxonomy, error)); ok {
		return rf(ctx, kind, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) domain.Taxonomy); ok {
		r0 = rf(ctx, kind, name)
	} else {
		r0 = ret.Get(0).(domain.Taxonomy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind, string) error); ok {
		r1 = rf(ctx, kind, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_CreateTaxonomy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaxonomy'
type MockMediaRepository_CreateTaxonomy_Call struct {
	*mock.Call
}

// CreateTaxonomy is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - name string
func (_e *MockMediaRepository_Expecter) CreateTaxonomy(ctx interface{}, kind interface{}, name interface{}) *MockMediaRepository_CreateTaxonomy_Call {
	return &MockMediaRepository_CreateTaxonomy_Call{Call: _e.mock.On("CreateTaxonomy", ctx, kind, name)}
}

func (_c *MockMediaRepository_CreateTaxonomy_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, name string)) *MockMediaRepository_CreateTaxonomy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string))
	})
	return _c
}

func (_c *MockMediaRepository_CreateTaxonomy_Call) Return(_a0 domain.Taxonomy, _a1 error) *MockMediaRepository_CreateTaxonomy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_CreateTaxonomy_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string) (domain.Taxonomy, error)) *MockMediaRepository_CreateTaxonomy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChapter provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) DeleteChapter(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_DeleteChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChapter'
type MockMediaRepository_DeleteChapter_Call struct {
	*mock.Call
}

// DeleteChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaRepository_Expecter) DeleteChapter(ctx interface{}, id interface{}) *MockMediaRepository_DeleteChapter_Call {
	return &MockMediaRepository_DeleteChapter_Call{Call: _e.mock.On("DeleteChapter", ctx, id)}
}

func (_c *MockMediaRepository_DeleteChapter_Call) Run(run func(ctx context.Context, id string)) *MockMediaRepository_DeleteChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_DeleteChapter_Call) Return(_a0 error) *MockMediaRepository_DeleteChapter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_DeleteChapter_Call) RunAndReturn(run func(context.Context, string) error) *MockMediaRepository_DeleteChapter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMedia provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) DeleteMedia(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_DeleteMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMedia'
type MockMediaRepository_DeleteMedia_Call struct {
	*mock.Call
}

// DeleteMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaRepository_Expecter) DeleteMedia(ctx interface{}, id interface{}) *MockMediaRepository_DeleteMedia_Call {
	return &MockMediaRepository_DeleteMedia_Call{Call: _e.mock.On("DeleteMedia", ctx, id)}
}

func (_c *MockMediaRepository_DeleteMedia_Call) Run(run func(ctx context.Context, id string)) *MockMediaRepository_DeleteMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_DeleteMedia_Call) Return(_a0 error) *MockMediaRepository_DeleteMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_DeleteMedia_Call) RunAndReturn(run func(context.Context, string) error) *MockMediaRepository_DeleteMedia_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePage provides a mock function with given fields: ctx, chapterID, idx
func (_m *MockMediaRepository) DeletePage(ctx context.Context, chapterID string, idx int) error {
	ret := _m.Called(ctx, chapterID, idx)

	if len(ret) == 0 {
		panic("no return value specified for DeletePage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, chapterID, idx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_DeletePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePage'
type MockMediaRepository_DeletePage_Call struct {
	*mock.Call
}

// DeletePage is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
//   - idx int
func (_e *MockMediaRepository_Expecter) DeletePage(ctx interface{}, chapterID interface{}, idx interface{}) *MockMediaRepository_DeletePage_Call {
	return &MockMediaRepository_DeletePage_Call{Call: _e.mock.On("DeletePage", ctx, chapterID, idx)}
}

func (_c *MockMediaRepository_DeletePage_Call) Run(run func(ctx context.Context, chapterID string, idx int)) *MockMediaRepository_DeletePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockMediaRepository_DeletePage_Call) Return(_a0 error) *MockMediaRepository_DeletePage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_DeletePage_Call) RunAndReturn(run func(context.Context, string, int) error) *MockMediaRepository_DeletePage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubType provides a mock function with given fields: ctx, slug
func (_m *MockMediaRepository) DeleteSubType(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_DeleteSubType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubType'
type MockMediaRepository_DeleteSubType_Call struct {
	*mock.Call
}

// DeleteSubType is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockMediaRepository_Expecter) DeleteSubType(ctx interface{}, slug interface{}) *MockMediaRepository_DeleteSubType_Call {
	return &MockMediaRepository_DeleteSubType_Call{Call: _e.mock.On("DeleteSubType", ctx, slug)}
}

func (_c *MockMediaRepository_DeleteSubType_Call) Run(run func(ctx context.Context, slug string)) *MockMediaRepository_DeleteSubType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_DeleteSubType_Call) Return(_a0 error) *MockMediaRepository_DeleteSubType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_DeleteSubType_Call) RunAndReturn(run func(context.Context, string) error) *MockMediaRepository_DeleteSubType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaxonomy provides a mock function with given fields: ctx, kind, id
func (_m *MockMediaRepository) DeleteTaxonomy(ctx context.Context, kind domain.TaxonomyKind, id string) error {
	ret := _m.Called(ctx, kind, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaxonomy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string) error); ok {
		r0 = rf(ctx, kind, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_DeleteTaxonomy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaxonomy'
type MockMediaRepository_DeleteTaxonomy_Call struct {
	*mock.Call
}

// DeleteTaxonomy is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - id string
func (_e *MockMediaRepository_Expecter) DeleteTaxonomy(ctx interface{}, kind interface{}, id interface{}) *MockMediaRepository_DeleteTaxonomy_Call {
	return &MockMediaRepository_DeleteTaxonomy_Call{Call: _e.mock.On("DeleteTaxonomy", ctx, kind, id)}
}

func (_c *MockMediaRepository_DeleteTaxonomy_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, id string)) *MockMediaRepository_DeleteTaxonomy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string))
	})
	return _c
}

func (_c *MockMediaRepository_DeleteTaxonomy_Call) Return(_a0 error) *MockMediaRepository_DeleteTaxonomy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_DeleteTaxonomy_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string) error) *MockMediaRepository_DeleteTaxonomy_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) Get(ctx context.Context, id string) (domain.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Media); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Media)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMediaRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaRepository_Expecter) Get(ctx interface{}, id interface{}) *MockMediaRepository_Get_Call {
	return &MockMediaRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMediaRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockMediaRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_Get_Call) Return(_a0 domain.Media, _a1 error) *MockMediaRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Media, error)) *MockMediaRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, sourceID, order, page, perPage, filter
func (_m *MockMediaRepository) List(ctx context.Context, sourceID string, order string, page int, perPage int, filter domain.CatalogFilter) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, order, page, perPage, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, domain.CatalogFilter) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, order, page, perPage, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, domain.CatalogFilter) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, order, page, perPage, filter)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int, domain.CatalogFilter) error); ok {
		r1 = rf(ctx, sourceID, order, page, perPage, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMediaRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - order string
//   - page int
//   - perPage int
//   - filter domain.CatalogFilter
func (_e *MockMediaRepository_Expecter) List(ctx interface{}, sourceID interface{}, order interface{}, page interface{}, perPage interface{}, filter interface{}) *MockMediaRepository_List_Call {
	return &MockMediaRepository_List_Call{Call: _e.mock.On("List", ctx, sourceID, order, page, perPage, filter)}
}

func (_c *MockMediaRepository_List_Call) Run(run func(ctx context.Context, sourceID string, order string, page int, perPage int, filter domain.CatalogFilter)) *MockMediaRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int), args[5].(domain.CatalogFilter))
	})
	return _c
}

func (_c *MockMediaRepository_List_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_List_Call) RunAndReturn(run func(context.Context, string, string, int, int, domain.CatalogFilter) (domain.MediaPage, error)) *MockMediaRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaxonomy provides a mock function with given fields: ctx, kind
func (_m *MockMediaRepository) ListTaxonomy(ctx context.Context, kind domain.TaxonomyKind) ([]domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for ListTaxonomy")
	}

	var r0 []domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind) ([]domain.Taxonomy, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind) []domain.Taxonomy); ok {
		r0 = rf(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Taxonomy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_ListTaxonomy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaxonomy'
type MockMediaRepository_ListTaxonomy_Call struct {
	*mock.Call
}

// ListTaxonomy is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
func (_e *MockMediaRepository_Expecter) ListTaxonomy(ctx interface{}, kind interface{}) *MockMediaRepository_ListTaxonomy_Call {
	return &MockMediaRepository_ListTaxonomy_Call{Call: _e.mock.On("ListTaxonomy", ctx, kind)}
}

func (_c *MockMediaRepository_ListTaxonomy_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind)) *MockMediaRepository_ListTaxonomy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind))
	})
	return _c
}

func (_c *MockMediaRepository_ListTaxonomy_Call) Return(_a0 []domain.Taxonomy, _a1 error) *MockMediaRepository_ListTaxonomy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_ListTaxonomy_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind) ([]domain.Taxonomy, error)) *MockMediaRepository_ListTaxonomy_Call {
	_c.Call.Return(run)
	return _c
}

// PageKeysForMedia provides a mock function with given fields: ctx, mediaID
func (_m *MockMediaRepository) PageKeysForMedia(ctx context.Context, mediaID string) ([]string, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for PageKeysForMedia")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_PageKeysForMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageKeysForMedia'
type MockMediaRepository_PageKeysForMedia_Call struct {
	*mock.Call
}

// PageKeysForMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID string
func (_e *MockMediaRepository_Expecter) PageKeysForMedia(ctx interface{}, mediaID interface{}) *MockMediaRepository_PageKeysForMedia_Call {
	return &MockMediaRepository_PageKeysForMedia_Call{Call: _e.mock.On("PageKeysForMedia", ctx, mediaID)}
}

func (_c *MockMediaRepository_PageKeysForMedia_Call) Run(run func(ctx context.Context, mediaID string)) *MockMediaRepository_PageKeysForMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_PageKeysForMedia_Call) Return(_a0 []string, _a1 error) *MockMediaRepository_PageKeysForMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_PageKeysForMedia_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockMediaRepository_PageKeysForMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Pages provides a mock function with given fields: ctx, chapterID
func (_m *MockMediaRepository) Pages(ctx context.Context, chapterID string) ([]domain.StoredPage, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for Pages")
	}

	var r0 []domain.StoredPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.StoredPage, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.StoredPage); ok {
		r0 = rf(ctx, chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StoredPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Pages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pages'
type MockMediaRepository_Pages_Call struct {
	*mock.Call
}

// Pages is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
func (_e *MockMediaRepository_Expecter) Pages(ctx interface{}, chapterID interface{}) *MockMediaRepository_Pages_Call {
	return &MockMediaRepository_Pages_Call{Call: _e.mock.On("Pages", ctx, chapterID)}
}

func (_c *MockMediaRepository_Pages_Call) Run(run func(ctx context.Context, chapterID string)) *MockMediaRepository_Pages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_Pages_Call) Return(_a0 []domain.StoredPage, _a1 error) *MockMediaRepository_Pages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Pages_Call) RunAndReturn(run func(context.Context, string) ([]domain.StoredPage, error)) *MockMediaRepository_Pages_Call {
	_c.Call.Return(run)
	return _c
}

// Recommend provides a mock function with given fields: ctx, sourceID, subTypes, exclude, page, perPage
func (_m *MockMediaRepository) Recommend(ctx context.Context, sourceID string, subTypes []string, exclude []string, page int, perPage int) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, subTypes, exclude, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for Recommend")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, []string, int, int) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, subTypes, exclude, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, []string, int, int) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, subTypes, exclude, page, perPage)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, []string, int, int) error); ok {
		r1 = rf(ctx, sourceID, subTypes, exclude, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Recommend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recommend'
type MockMediaRepository_Recommend_Call struct {
	*mock.Call
}

// Recommend is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - subTypes []string
//   - exclude []string
//   - page int
//   - perPage int
func (_e *MockMediaRepository_Expecter) Recommend(ctx interface{}, sourceID interface{}, subTypes interface{}, exclude interface{}, page interface{}, perPage interface{}) *MockMediaRepository_Recommend_Call {
	return &MockMediaRepository_Recommend_Call{Call: _e.mock.On("Recommend", ctx, sourceID, subTypes, exclude, page, perPage)}
}

func (_c *MockMediaRepository_Recommend_Call) Run(run func(ctx context.Context, sourceID string, subTypes []string, exclude []string, page int, perPage int)) *MockMediaRepository_Recommend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].([]string), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockMediaRepository_Recommend_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaRepository_Recommend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Recommend_Call) RunAndReturn(run func(context.Context, string, []string, []string, int, int) (domain.MediaPage, error)) *MockMediaRepository_Recommend_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, sourceID, query, page, perPage, filter
func (_m *MockMediaRepository) Search(ctx context.Context, sourceID string, query string, page int, perPage int, filter domain.CatalogFilter) (domain.MediaPage, error) {
	ret := _m.Called(ctx, sourceID, query, page, perPage, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.MediaPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, domain.CatalogFilter) (domain.MediaPage, error)); ok {
		return rf(ctx, sourceID, query, page, perPage, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, domain.CatalogFilter) domain.MediaPage); ok {
		r0 = rf(ctx, sourceID, query, page, perPage, filter)
	} else {
		r0 = ret.Get(0).(domain.MediaPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int, domain.CatalogFilter) error); ok {
		r1 = rf(ctx, sourceID, query, page, perPage, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMediaRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
//   - query string
//   - page int
//   - perPage int
//   - filter domain.CatalogFilter
func (_e *MockMediaRepository_Expecter) Search(ctx interface{}, sourceID interface{}, query interface{}, page interface{}, perPage interface{}, filter interface{}) *MockMediaRepository_Search_Call {
	return &MockMediaRepository_Search_Call{Call: _e.mock.On("Search", ctx, sourceID, query, page, perPage, filter)}
}

func (_c *MockMediaRepository_Search_Call) Run(run func(ctx context.Context, sourceID string, query string, page int, perPage int, filter domain.CatalogFilter)) *MockMediaRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int), args[5].(domain.CatalogFilter))
	})
	return _c
}

func (_c *MockMediaRepository_Search_Call) Return(_a0 domain.MediaPage, _a1 error) *MockMediaRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Search_Call) RunAndReturn(run func(context.Context, string, string, int, int, domain.CatalogFilter) (domain.MediaPage, error)) *MockMediaRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SetMediaCover provides a mock function with given fields: ctx, mediaID, coverURL
func (_m *MockMediaRepository) SetMediaCover(ctx context.Context, mediaID string, coverURL string) error {
	ret := _m.Called(ctx, mediaID, coverURL)

	if len(ret) == 0 {
		panic("no return value specified for SetMediaCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, mediaID, coverURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_SetMediaCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMediaCover'
type MockMediaRepository_SetMediaCover_Call struct {
	*mock.Call
}

// SetMediaCover is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID string
//   - coverURL string
func (_e *MockMediaRepository_Expecter) SetMediaCover(ctx interface{}, mediaID interface{}, coverURL interface{}) *MockMediaRepository_SetMediaCover_Call {
	return &MockMediaRepository_SetMediaCover_Call{Call: _e.mock.On("SetMediaCover", ctx, mediaID, coverURL)}
}

func (_c *MockMediaRepository_SetMediaCover_Call) Run(run func(ctx context.Context, mediaID string, coverURL string)) *MockMediaRepository_SetMediaCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMediaRepository_SetMediaCover_Call) Return(_a0 error) *MockMediaRepository_SetMediaCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_SetMediaCover_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMediaRepository_SetMediaCover_Call {
	_c.Call.Return(run)
	return _c
}

// SubTypeVocab provides a mock function with given fields: ctx
func (_m *MockMediaRepository) SubTypeVocab(ctx context.Context) (map[domain.MediaType][]domain.SubType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubTypeVocab")
	}

	var r0 map[domain.MediaType][]domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[domain.MediaType][]domain.SubType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[domain.MediaType][]domain.SubType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.MediaType][]domain.SubType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_SubTypeVocab_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTypeVocab'
type MockMediaRepository_SubTypeVocab_Call struct {
	*mock.Call
}

// SubTypeVocab is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMediaRepository_Expecter) SubTypeVocab(ctx interface{}) *MockMediaRepository_SubTypeVocab_Call {
	return &MockMediaRepository_SubTypeVocab_Call{Call: _e.mock.On("SubTypeVocab", ctx)}
}

func (_c *MockMediaRepository_SubTypeVocab_Call) Run(run func(ctx context.Context)) *MockMediaRepository_SubTypeVocab_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMediaRepository_SubTypeVocab_Call) Return(_a0 map[domain.MediaType][]domain.SubType, _a1 error) *MockMediaRepository_SubTypeVocab_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_SubTypeVocab_Call) RunAndReturn(run func(context.Context) (map[domain.MediaType][]domain.SubType, error)) *MockMediaRepository_SubTypeVocab_Call {
	_c.Call.Return(run)
	return _c
}

// SubTypes provides a mock function with given fields: ctx, sourceID
func (_m *MockMediaRepository) SubTypes(ctx context.Context, sourceID string) ([]domain.SubType, error) {
	ret := _m.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for SubTypes")
	}

	var r0 []domain.SubType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SubType, error)); ok {
		return rf(ctx, sourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SubType); ok {
		r0 = rf(ctx, sourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SubType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_SubTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTypes'
type MockMediaRepository_SubTypes_Call struct {
	*mock.Call
}

// SubTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID string
func (_e *MockMediaRepository_Expecter) SubTypes(ctx interface{}, sourceID interface{}) *MockMediaRepository_SubTypes_Call {
	return &MockMediaRepository_SubTypes_Call{Call: _e.mock.On("SubTypes", ctx, sourceID)}
}

func (_c *MockMediaRepository_SubTypes_Call) Run(run func(ctx context.Context, sourceID string)) *MockMediaRepository_SubTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaRepository_SubTypes_Call) Return(_a0 []domain.SubType, _a1 error) *MockMediaRepository_SubTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_SubTypes_Call) RunAndReturn(run func(context.Context, string) ([]domain.SubType, error)) *MockMediaRepository_SubTypes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChapter provides a mock function with given fields: ctx, c
func (_m *MockMediaRepository) UpdateChapter(ctx context.Context, c domain.Chapter) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Chapter) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_UpdateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChapter'
type MockMediaRepository_UpdateChapter_Call struct {
	*mock.Call
}

// UpdateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - c domain.Chapter
func (_e *MockMediaRepository_Expecter) UpdateChapter(ctx interface{}, c interface{}) *MockMediaRepository_UpdateChapter_Call {
	return &MockMediaRepository_UpdateChapter_Call{Call: _e.mock.On("UpdateChapter", ctx, c)}
}

func (_c *MockMediaRepository_UpdateChapter_Call) Run(run func(ctx context.Context, c domain.Chapter)) *MockMediaRepository_UpdateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Chapter))
	})
	return _c
}

func (_c *MockMediaRepository_UpdateChapter_Call) Return(_a0 error) *MockMediaRepository_UpdateChapter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_UpdateChapter_Call) RunAndReturn(run func(context.Context, domain.Chapter) error) *MockMediaRepository_UpdateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMedia provides a mock function with given fields: ctx, m
func (_m *MockMediaRepository) UpdateMedia(ctx context.Context, m domain.Media) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Media) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_UpdateMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMedia'
type MockMediaRepository_UpdateMedia_Call struct {
	*mock.Call
}

// UpdateMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - m domain.Media
func (_e *MockMediaRepository_Expecter) UpdateMedia(ctx interface{}, m interface{}) *MockMediaRepository_UpdateMedia_Call {
	return &MockMediaRepository_UpdateMedia_Call{Call: _e.mock.On("UpdateMedia", ctx, m)}
}

func (_c *MockMediaRepository_UpdateMedia_Call) Run(run func(ctx context.Context, m domain.Media)) *MockMediaRepository_UpdateMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Media))
	})
	return _c
}

func (_c *MockMediaRepository_UpdateMedia_Call) Return(_a0 error) *MockMediaRepository_UpdateMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_UpdateMedia_Call) RunAndReturn(run func(context.Context, domain.Media) error) *MockMediaRepository_UpdateMedia_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubType provides a mock function with given fields: ctx, slug, st
func (_m *MockMediaRepository) UpdateSubType(ctx context.Context, slug string, st domain.SubType) error {
	ret := _m.Called(ctx, slug, st)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubType) error); ok {
		r0 = rf(ctx, slug, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_UpdateSubType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubType'
type MockMediaRepository_UpdateSubType_Call struct {
	*mock.Call
}

// UpdateSubType is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - st domain.SubType
func (_e *MockMediaRepository_Expecter) UpdateSubType(ctx interface{}, slug interface{}, st interface{}) *MockMediaRepository_UpdateSubType_Call {
	return &MockMediaRepository_UpdateSubType_Call{Call: _e.mock.On("UpdateSubType", ctx, slug, st)}
}

func (_c *MockMediaRepository_UpdateSubType_Call) Run(run func(ctx context.Context, slug string, st domain.SubType)) *MockMediaRepository_UpdateSubType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubType))
	})
	return _c
}

func (_c *MockMediaRepository_UpdateSubType_Call) Return(_a0 error) *MockMediaRepository_UpdateSubType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_UpdateSubType_Call) RunAndReturn(run func(context.Context, string, domain.SubType) error) *MockMediaRepository_UpdateSubType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaxonomy provides a mock function with given fields: ctx, kind, id, name
func (_m *MockMediaRepository) UpdateTaxonomy(ctx context.Context, kind domain.TaxonomyKind, id string, name string) (domain.Taxonomy, error) {
	ret := _m.Called(ctx, kind, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaxonomy")
	}

	var r0 domain.Taxonomy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string, string) (domain.Taxonomy, error)); ok {
		return rf(ctx, kind, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaxonomyKind, string, string) domain.Taxonomy); ok {
		r0 = rf(ctx, kind, id, name)
	} else {
		r0 = ret.Get(0).(domain.Taxonomy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaxonomyKind, string, string) error); ok {
		r1 = rf(ctx, kind, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_UpdateTaxonomy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaxonomy'
type MockMediaRepository_UpdateTaxonomy_Call struct {
	*mock.Call
}

// UpdateTaxonomy is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.TaxonomyKind
//   - id string
//   - name string
func (_e *MockMediaRepository_Expecter) UpdateTaxonomy(ctx interface{}, kind interface{}, id interface{}, name interface{}) *MockMediaRepository_UpdateTaxonomy_Call {
	return &MockMediaRepository_UpdateTaxonomy_Call{Call: _e.mock.On("UpdateTaxonomy", ctx, kind, id, name)}
}

func (_c *MockMediaRepository_UpdateTaxonomy_Call) Run(run func(ctx context.Context, kind domain.TaxonomyKind, id string, name string)) *MockMediaRepository_UpdateTaxonomy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaxonomyKind), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMediaRepository_UpdateTaxonomy_Call) Return(_a0 domain.Taxonomy, _a1 error) *MockMediaRepository_UpdateTaxonomy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_UpdateTaxonomy_Call) RunAndReturn(run func(context.Context, domain.TaxonomyKind, string, string) (domain.Taxonomy, error)) *MockMediaRepository_UpdateTaxonomy_Call {
	_c.Call.Return(run)
	return _c
}

// ValidSubType provides a mock function with given fields: ctx, t, slug
func (_m *MockMediaRepository) ValidSubType(ctx context.Context, t domain.MediaType, slug string) (bool, error) {
	ret := _m.Called(ctx, t, slug)

	if len(ret) == 0 {
		panic("no return value specified for ValidSubType")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MediaType, string) (bool, error)); ok {
		return rf(ctx, t, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MediaType, string) bool); ok {
		r0 = rf(ctx, t, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MediaType, string) error); ok {
		r1 = rf(ctx, t, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_ValidSubType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidSubType'
type MockMediaRepository_ValidSubType_Call struct {
	*mock.Call
}

// ValidSubType is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.MediaType
//   - slug string
func (_e *MockMediaRepository_Expecter) ValidSubType(ctx interface{}, t interface{}, slug interface{}) *MockMediaRepository_ValidSubType_Call {
	return &MockMediaRepository_ValidSubType_Call{Call: _e.mock.On("ValidSubType", ctx, t, slug)}
}

func (_c *MockMediaRepository_ValidSubType_Call) Run(run func(ctx context.Context, t domain.MediaType, slug string)) *MockMediaRepository_ValidSubType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MediaType), args[2].(string))
	})
	return _c
}

func (_c *MockMediaRepository_ValidSubType_Call) Return(_a0 bool, _a1 error) *MockMediaRepository_ValidSubType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_ValidSubType_Call) RunAndReturn(run func(context.Context, domain.MediaType, string) (bool, error)) *MockMediaRepository_ValidSubType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaRepository creates a new instance of MockMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaRepository {
	mock := &MockMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
