// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockSourceRepository is an autogenerated mock type for the SourceRepository type
type MockSourceRepository struct {
	mock.Mock
}

type MockSourceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceRepository) EXPECT() *MockSourceRepository_Expecter {
	return &MockSourceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockSourceRepository) Create(ctx context.Context, s domain.Source) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Source) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSourceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSourceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Source
func (_e *MockSourceRepository_Expecter) Create(ctx interface{}, s interface{}) *MockSourceRepository_Create_Call {
	return &MockSourceRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockSourceRepository_Create_Call) Run(run func(ctx context.Context, s domain.Source)) *MockSourceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Source))
	})
	return _c
}

func (_c *MockSourceRepository_Create_Call) Return(_a0 error) *MockSourceRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSourceRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Source) error) *MockSourceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSourceRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSourceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSourceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSourceRepository_Delete_Call {
	return &MockSourceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSourceRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSourceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceRepository_Delete_Call) Return(_a0 error) *MockSourceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSourceRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSourceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *MockSourceRepository) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSourceRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockSourceRepository_Exists_Call {
	return &MockSourceRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockSourceRepository_Exists_Call) Run(run func(ctx context.Context, id string)) *MockSourceRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockSourceRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSourceRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockSourceRepository) Get(ctx context.Context, id string) (domain.Source, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Source, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Source); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSourceRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceRepository_Expecter) Get(ctx interface{}, id interface{}) *MockSourceRepository_Get_Call {
	return &MockSourceRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSourceRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockSourceRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceRepository_Get_Call) Return(_a0 domain.Source, _a1 error) *MockSourceRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceRepository_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Source, error)) *MockSourceRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, enabledOnly
func (_m *MockSourceRepository) List(ctx context.Context, enabledOnly bool) ([]domain.Source, error) {
	ret := _m.Called(ctx, enabledOnly)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Source, error)); ok {
		return rf(ctx, enabledOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []domain.Source); ok {
		r0 = rf(ctx, enabledOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, enabledOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSourceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - enabledOnly bool
func (_e *MockSourceRepository_Expecter) List(ctx interface{}, enabledOnly interface{}) *MockSourceRepository_List_Call {
	return &MockSourceRepository_List_Call{Call: _e.mock.On("List", ctx, enabledOnly)}
}

func (_c *MockSourceRepository_List_Call) Run(run func(ctx context.Context, enabledOnly bool)) *MockSourceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockSourceRepository_List_Call) Return(_a0 []domain.Source, _a1 error) *MockSourceRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceRepository_List_Call) RunAndReturn(run func(context.Context, bool) ([]domain.Source, error)) *MockSourceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MediaCount provides a mock function with given fields: ctx, id
func (_m *MockSourceRepository) MediaCount(ctx context.Context, id string) (int, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MediaCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceRepository_MediaCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MediaCount'
type MockSourceRepository_MediaCount_Call struct {
	*mock.Call
}

// MediaCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSourceRepository_Expecter) MediaCount(ctx interface{}, id interface{}) *MockSourceRepository_MediaCount_Call {
	return &MockSourceRepository_MediaCount_Call{Call: _e.mock.On("MediaCount", ctx, id)}
}

func (_c *MockSourceRepository_MediaCount_Call) Run(run func(ctx context.Context, id string)) *MockSourceRepository_MediaCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSourceRepository_MediaCount_Call) Return(_a0 int, _a1 error) *MockSourceRepository_MediaCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceRepository_MediaCount_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockSourceRepository_MediaCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s
func (_m *MockSourceRepository) Update(ctx context.Context, s domain.Source) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Source) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSourceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSourceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Source
func (_e *MockSourceRepository_Expecter) Update(ctx interface{}, s interface{}) *MockSourceRepository_Update_Call {
	return &MockSourceRepository_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *MockSourceRepository_Update_Call) Run(run func(ctx context.Context, s domain.Source)) *MockSourceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Source))
	})
	return _c
}

func (_c *MockSourceRepository_Update_Call) Return(_a0 error) *MockSourceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSourceRepository_Update_Call) RunAndReturn(run func(context.Context, domain.Source) error) *MockSourceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourceRepository creates a new instance of MockSourceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceRepository {
	mock := &MockSourceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
