// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockCoverMirrorQueue is an autogenerated mock type for the CoverMirrorQueue type
type MockCoverMirrorQueue struct {
	mock.Mock
}

type MockCoverMirrorQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoverMirrorQueue) EXPECT() *MockCoverMirrorQueue_Expecter {
	return &MockCoverMirrorQueue_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, job
func (_m *MockCoverMirrorQueue) Enqueue(ctx context.Context, job domain.CoverMirrorJob) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CoverMirrorJob) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCoverMirrorQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockCoverMirrorQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.CoverMirrorJob
func (_e *MockCoverMirrorQueue_Expecter) Enqueue(ctx interface{}, job interface{}) *MockCoverMirrorQueue_Enqueue_Call {
	return &MockCoverMirrorQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, job)}
}

func (_c *MockCoverMirrorQueue_Enqueue_Call) Run(run func(ctx context.Context, job domain.CoverMirrorJob)) *MockCoverMirrorQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CoverMirrorJob))
	})
	return _c
}

func (_c *MockCoverMirrorQueue_Enqueue_Call) Return(_a0 error) *MockCoverMirrorQueue_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoverMirrorQueue_Enqueue_Call) RunAndReturn(run func(context.Context, domain.CoverMirrorJob) error) *MockCoverMirrorQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoverMirrorQueue creates a new instance of MockCoverMirrorQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoverMirrorQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoverMirrorQueue {
	mock := &MockCoverMirrorQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
