// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// DeleteObjects provides a mock function with given fields: ctx, keys
func (_m *MockObjectStore) DeleteObjects(ctx context.Context, keys []string) error {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_DeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjects'
type MockObjectStore_DeleteObjects_Call struct {
	*mock.Call
}

// DeleteObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockObjectStore_Expecter) DeleteObjects(ctx interface{}, keys interface{}) *MockObjectStore_DeleteObjects_Call {
	return &MockObjectStore_DeleteObjects_Call{Call: _e.mock.On("DeleteObjects", ctx, keys)}
}

func (_c *MockObjectStore_DeleteObjects_Call) Run(run func(ctx context.Context, keys []string)) *MockObjectStore_DeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockObjectStore_DeleteObjects_Call) Return(_a0 error) *MockObjectStore_DeleteObjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_DeleteObjects_Call) RunAndReturn(run func(context.Context, []string) error) *MockObjectStore_DeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Get(ctx context.Context, key string) ([]byte, string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockObjectStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObjectStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Get(ctx interface{}, key interface{}) *MockObjectStore_Get_Call {
	return &MockObjectStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockObjectStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Get_Call) Return(_a0 []byte, _a1 string, _a2 error) *MockObjectStore_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockObjectStore_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, string, error)) *MockObjectStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGet provides a mock function with given fields: ctx, key, ttl
func (_m *MockObjectStore) PresignGet(ctx context.Context, key string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignGet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_PresignGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGet'
type MockObjectStore_PresignGet_Call struct {
	*mock.Call
}

// PresignGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockObjectStore_Expecter) PresignGet(ctx interface{}, key interface{}, ttl interface{}) *MockObjectStore_PresignGet_Call {
	return &MockObjectStore_PresignGet_Call{Call: _e.mock.On("PresignGet", ctx, key, ttl)}
}

func (_c *MockObjectStore_PresignGet_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockObjectStore_PresignGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockObjectStore_PresignGet_Call) Return(_a0 string, _a1 error) *MockObjectStore_PresignGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_PresignGet_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockObjectStore_PresignGet_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPut provides a mock function with given fields: ctx, key, ttl, contentType
func (_m *MockObjectStore) PresignPut(ctx context.Context, key string, ttl time.Duration, contentType string) (string, error) {
	ret := _m.Called(ctx, key, ttl, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPut")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) (string, error)); ok {
		return rf(ctx, key, ttl, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) string); ok {
		r0 = rf(ctx, key, ttl, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, string) error); ok {
		r1 = rf(ctx, key, ttl, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_PresignPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPut'
type MockObjectStore_PresignPut_Call struct {
	*mock.Call
}

// PresignPut is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - contentType string
func (_e *MockObjectStore_Expecter) PresignPut(ctx interface{}, key interface{}, ttl interface{}, contentType interface{}) *MockObjectStore_PresignPut_Call {
	return &MockObjectStore_PresignPut_Call{Call: _e.mock.On("PresignPut", ctx, key, ttl, contentType)}
}

func (_c *MockObjectStore_PresignPut_Call) Run(run func(ctx context.Context, key string, ttl time.Duration, contentType string)) *MockObjectStore_PresignPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), args[3].(string))
	})
	return _c
}

func (_c *MockObjectStore_PresignPut_Call) Return(_a0 string, _a1 error) *MockObjectStore_PresignPut_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_PresignPut_Call) RunAndReturn(run func(context.Context, string, time.Duration, string) (string, error)) *MockObjectStore_PresignPut_Call {
	_c.Call.Return(run)
	return _c
}

// PublicURL provides a mock function with given fields: key
func (_m *MockObjectStore) PublicURL(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockObjectStore_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockObjectStore_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - key string
func (_e *MockObjectStore_Expecter) PublicURL(key interface{}) *MockObjectStore_PublicURL_Call {
	return &MockObjectStore_PublicURL_Call{Call: _e.mock.On("PublicURL", key)}
}

func (_c *MockObjectStore_PublicURL_Call) Run(run func(key string)) *MockObjectStore_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockObjectStore_PublicURL_Call) Return(_a0 string) *MockObjectStore_PublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_PublicURL_Call) RunAndReturn(run func(string) string) *MockObjectStore_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, data, contentType
func (_m *MockObjectStore) Put(ctx context.Context, key string, data []byte, contentType string) error {
	ret := _m.Called(ctx, key, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = rf(ctx, key, data, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - contentType string
func (_e *MockObjectStore_Expecter) Put(ctx interface{}, key interface{}, data interface{}, contentType interface{}) *MockObjectStore_Put_Call {
	return &MockObjectStore_Put_Call{Call: _e.mock.On("Put", ctx, key, data, contentType)}
}

func (_c *MockObjectStore_Put_Call) Run(run func(ctx context.Context, key string, data []byte, contentType string)) *MockObjectStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockObjectStore_Put_Call) Return(_a0 error) *MockObjectStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Put_Call) RunAndReturn(run func(context.Context, string, []byte, string) error) *MockObjectStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
