// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCleanupQueue is an autogenerated mock type for the CleanupQueue type
type MockCleanupQueue struct {
	mock.Mock
}

type MockCleanupQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleanupQueue) EXPECT() *MockCleanupQueue_Expecter {
	return &MockCleanupQueue_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, keys
func (_m *MockCleanupQueue) Enqueue(ctx context.Context, keys []string) error {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockCleanupQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockCleanupQueue_Expecter) Enqueue(ctx interface{}, keys interface{}) *MockCleanupQueue_Enqueue_Call {
	return &MockCleanupQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, keys)}
}

func (_c *MockCleanupQueue_Enqueue_Call) Run(run func(ctx context.Context, keys []string)) *MockCleanupQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCleanupQueue_Enqueue_Call) Return(_a0 error) *MockCleanupQueue_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupQueue_Enqueue_Call) RunAndReturn(run func(context.Context, []string) error) *MockCleanupQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueuePrefixes provides a mock function with given fields: ctx, prefixes
func (_m *MockCleanupQueue) EnqueuePrefixes(ctx context.Context, prefixes []string) error {
	ret := _m.Called(ctx, prefixes)

	if len(ret) == 0 {
		panic("no return value specified for EnqueuePrefixes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, prefixes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupQueue_EnqueuePrefixes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueuePrefixes'
type MockCleanupQueue_EnqueuePrefixes_Call struct {
	*mock.Call
}

// EnqueuePrefixes is a helper method to define mock.On call
//   - ctx context.Context
//   - prefixes []string
func (_e *MockCleanupQueue_Expecter) EnqueuePrefixes(ctx interface{}, prefixes interface{}) *MockCleanupQueue_EnqueuePrefixes_Call {
	return &MockCleanupQueue_EnqueuePrefixes_Call{Call: _e.mock.On("EnqueuePrefixes", ctx, prefixes)}
}

func (_c *MockCleanupQueue_EnqueuePrefixes_Call) Run(run func(ctx context.Context, prefixes []string)) *MockCleanupQueue_EnqueuePrefixes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCleanupQueue_EnqueuePrefixes_Call) Return(_a0 error) *MockCleanupQueue_EnqueuePrefixes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupQueue_EnqueuePrefixes_Call) RunAndReturn(run func(context.Context, []string) error) *MockCleanupQueue_EnqueuePrefixes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCleanupQueue creates a new instance of MockCleanupQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupQueue {
	mock := &MockCleanupQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
