// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockAdRepository is an autogenerated mock type for the AdRepository type
type MockAdRepository struct {
	mock.Mock
}

type MockAdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdRepository) EXPECT() *MockAdRepository_Expecter {
	return &MockAdRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockAdRepository) Create(ctx context.Context, a domain.StoredAd) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StoredAd) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a domain.StoredAd
func (_e *MockAdRepository_Expecter) Create(ctx interface{}, a interface{}) *MockAdRepository_Create_Call {
	return &MockAdRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAdRepository_Create_Call) Run(run func(ctx context.Context, a domain.StoredAd)) *MockAdRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StoredAd))
	})
	return _c
}

func (_c *MockAdRepository_Create_Call) Return(_a0 error) *MockAdRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Create_Call) RunAndReturn(run func(context.Context, domain.StoredAd) error) *MockAdRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAdRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAdRepository_Delete_Call {
	return &MockAdRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAdRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAdRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdRepository_Delete_Call) Return(_a0 error) *MockAdRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAdRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAdRepository) Get(ctx context.Context, id string) (domain.StoredAd, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StoredAd, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StoredAd); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.StoredAd)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAdRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAdRepository_Get_Call {
	return &MockAdRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAdRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockAdRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdRepository_Get_Call) Return(_a0 domain.StoredAd, _a1 error) *MockAdRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdRepository_Get_Call) RunAndReturn(run func(context.Context, string) (domain.StoredAd, error)) *MockAdRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, activeOnly, placement
func (_m *MockAdRepository) List(ctx context.Context, activeOnly bool, placement string) ([]domain.StoredAd, error) {
	ret := _m.Called(ctx, activeOnly, placement)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.StoredAd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) ([]domain.StoredAd, error)); ok {
		return rf(ctx, activeOnly, placement)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) []domain.StoredAd); ok {
		r0 = rf(ctx, activeOnly, placement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StoredAd)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, string) error); ok {
		r1 = rf(ctx, activeOnly, placement)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAdRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - activeOnly bool
//   - placement string
func (_e *MockAdRepository_Expecter) List(ctx interface{}, activeOnly interface{}, placement interface{}) *MockAdRepository_List_Call {
	return &MockAdRepository_List_Call{Call: _e.mock.On("List", ctx, activeOnly, placement)}
}

func (_c *MockAdRepository_List_Call) Run(run func(ctx context.Context, activeOnly bool, placement string)) *MockAdRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(string))
	})
	return _c
}

func (_c *MockAdRepository_List_Call) Return(_a0 []domain.StoredAd, _a1 error) *MockAdRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdRepository_List_Call) RunAndReturn(run func(context.Context, bool, string) ([]domain.StoredAd, error)) *MockAdRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, a
func (_m *MockAdRepository) Update(ctx context.Context, a domain.StoredAd) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StoredAd) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - a domain.StoredAd
func (_e *MockAdRepository_Expecter) Update(ctx interface{}, a interface{}) *MockAdRepository_Update_Call {
	return &MockAdRepository_Update_Call{Call: _e.mock.On("Update", ctx, a)}
}

func (_c *MockAdRepository_Update_Call) Run(run func(ctx context.Context, a domain.StoredAd)) *MockAdRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StoredAd))
	})
	return _c
}

func (_c *MockAdRepository_Update_Call) Return(_a0 error) *MockAdRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Update_Call) RunAndReturn(run func(context.Context, domain.StoredAd) error) *MockAdRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdRepository creates a new instance of MockAdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdRepository {
	mock := &MockAdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
