// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// ReplacePages provides a mock function with given fields: ctx, chapterID, pages
func (_m *MockJobRepository) ReplacePages(ctx context.Context, chapterID string, pages []domain.StoredPage) error {
	ret := _m.Called(ctx, chapterID, pages)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.StoredPage) error); ok {
		r0 = rf(ctx, chapterID, pages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_ReplacePages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePages'
type MockJobRepository_ReplacePages_Call struct {
	*mock.Call
}

// ReplacePages is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
//   - pages []domain.StoredPage
func (_e *MockJobRepository_Expecter) ReplacePages(ctx interface{}, chapterID interface{}, pages interface{}) *MockJobRepository_ReplacePages_Call {
	return &MockJobRepository_ReplacePages_Call{Call: _e.mock.On("ReplacePages", ctx, chapterID, pages)}
}

func (_c *MockJobRepository_ReplacePages_Call) Run(run func(ctx context.Context, chapterID string, pages []domain.StoredPage)) *MockJobRepository_ReplacePages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.StoredPage))
	})
	return _c
}

func (_c *MockJobRepository_ReplacePages_Call) Return(_a0 error) *MockJobRepository_ReplacePages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_ReplacePages_Call) RunAndReturn(run func(context.Context, string, []domain.StoredPage) error) *MockJobRepository_ReplacePages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
