// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/triasbrata/mihon-manga-server/internal/domain"
)

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, job
func (_m *MockJobRepository) Create(ctx context.Context, job domain.ConvertJob) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConvertJob) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.ConvertJob
func (_e *MockJobRepository_Expecter) Create(ctx interface{}, job interface{}) *MockJobRepository_Create_Call {
	return &MockJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, job)}
}

func (_c *MockJobRepository_Create_Call) Run(run func(ctx context.Context, job domain.ConvertJob)) *MockJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ConvertJob))
	})
	return _c
}

func (_c *MockJobRepository_Create_Call) Return(_a0 error) *MockJobRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_Create_Call) RunAndReturn(run func(context.Context, domain.ConvertJob) error) *MockJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockJobRepository) Get(ctx context.Context, id string) (domain.ConvertJob, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.ConvertJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ConvertJob, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ConvertJob); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.ConvertJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockJobRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockJobRepository_Expecter) Get(ctx interface{}, id interface{}) *MockJobRepository_Get_Call {
	return &MockJobRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockJobRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockJobRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJobRepository_Get_Call) Return(_a0 domain.ConvertJob, _a1 error) *MockJobRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_Get_Call) RunAndReturn(run func(context.Context, string) (domain.ConvertJob, error)) *MockJobRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePages provides a mock function with given fields: ctx, chapterID, pages
func (_m *MockJobRepository) ReplacePages(ctx context.Context, chapterID string, pages []domain.StoredPage) error {
	ret := _m.Called(ctx, chapterID, pages)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.StoredPage) error); ok {
		r0 = rf(ctx, chapterID, pages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_ReplacePages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePages'
type MockJobRepository_ReplacePages_Call struct {
	*mock.Call
}

// ReplacePages is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID string
//   - pages []domain.StoredPage
func (_e *MockJobRepository_Expecter) ReplacePages(ctx interface{}, chapterID interface{}, pages interface{}) *MockJobRepository_ReplacePages_Call {
	return &MockJobRepository_ReplacePages_Call{Call: _e.mock.On("ReplacePages", ctx, chapterID, pages)}
}

func (_c *MockJobRepository_ReplacePages_Call) Run(run func(ctx context.Context, chapterID string, pages []domain.StoredPage)) *MockJobRepository_ReplacePages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.StoredPage))
	})
	return _c
}

func (_c *MockJobRepository_ReplacePages_Call) Return(_a0 error) *MockJobRepository_ReplacePages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_ReplacePages_Call) RunAndReturn(run func(context.Context, string, []domain.StoredPage) error) *MockJobRepository_ReplacePages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, pageCount, errMsg
func (_m *MockJobRepository) UpdateStatus(ctx context.Context, id string, status domain.ConvertStatus, pageCount int, errMsg string) error {
	ret := _m.Called(ctx, id, status, pageCount, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ConvertStatus, int, string) error); ok {
		r0 = rf(ctx, id, status, pageCount, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockJobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status domain.ConvertStatus
//   - pageCount int
//   - errMsg string
func (_e *MockJobRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, pageCount interface{}, errMsg interface{}) *MockJobRepository_UpdateStatus_Call {
	return &MockJobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, pageCount, errMsg)}
}

func (_c *MockJobRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status domain.ConvertStatus, pageCount int, errMsg string)) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ConvertStatus), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) Return(_a0 error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, domain.ConvertStatus, int, string) error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
